### PR TITLE
[ADD] pre-commit config

### PR DESCRIPTION
**Pull request by mathdugre**
## Description
This PR proposes the addition of code standards to extend #544.

It uses [pre-commit](https://pre-commit.com/) to optionally run checks before every commit with the goal to accelerate development and minimize mistakes.
The *hooks* configurations is described in the `.pre-commit-config.yaml` file.

The proposed hooks include various functional and style standards such as: Python / JSON / YAML syntax check, [black](https://github.com/psf/black), flake8, documentation style, Docker linter, and others.

In addition, this PR adds a new job to the CircleCI workflow to do QA tests.
This new job is independent of the current test job. Thus does not affect the info status for the datasets.
The new workflow would look as follow:
2021-03-04_16-14-03_screenshot

## Related issues (optional)
PR #544

### CODE REVIEW

**Comment by cmadjar** [comment]
@mathdugre I am not sure how I could test this? Could you enlighten me?

Also, it looks like this PR is not running the Circle Ci tests for some reason.

**Comment by mathdugre** [comment]
@cmadjar, I triggered a rerun of the test to execute them on the CONP organization.
Once CircleCI is done running, you could have a look at the new QA workflow. This should output a report about the different pre-commit hooks used and the ones having either warnings or errors.

**Comment by cmadjar** [comment]
@mathdugre could you merge master into your branch? The issue reported in Circle CI should be fixed now in master. Thanks!

**Comment by mathdugre** [comment]
@cmadjar, I'll wait until #550 is merged to update this PR with the master branch. They will likely result in a merge conflict.

**Comment by cmadjar** [comment]
@mathdugre ready for merge with master branch and conflict resolution!

**Comment by cmadjar** [comment]
@mathdugre looks like the QA workflow is failing.

**Comment by mathdugre** [comment]
@cmadjar, I saw only that pre-commit also has a GitHub action providing more functionalities. I removed the circle implementation to convert it to GitHub action. It also removes the need to add *pre-commit* to our dependencies.

As for the QA (now Linting workflow), it shows as fail because:
1. some of the coding standards are not yet respected.
2. some tools auto-apply and pre-commit consider that as a failure. Pre-commit enforces developers to run the tools themselves to minimize overall errors.

We should probably discuss which exceptions we want to allow in those coding standards.
Moreover, apply the code standard should probably be done as part of a future PR(s).

**Comment by cmadjar** [comment]
@mathdugre can you merge conp/master to your branch? I have a feeling the 1000GenomesProject error has been fixed since your last merge with conp/master. That should resolve the CircleCI error for that project.

Not sure what is happening for the MRI_and_unbiased dataset though.

**Comment by cmadjar** [comment]
actually, if I remember correctly, the file that gives the error on CircleCI for MRI_and_unbiased* dataset is a big file and this might be resolved once we merge #567?

**Comment by mathdugre** [comment]
@cmadjar , I think the test failure are unrelated to the changes since this PR does not modify the test suite in CircleCI. That is, the new GitHub workflow is independent of CircleCI.

**Comment by cmadjar** [comment]
@mathdugre This is still failing Circle CI. 

The guilty files that failed the test download are:
- projects/1000GenomesProject/1KGP_chrY.vcf.gz: I can download manually that dataset on the master branch of conp-dataset. However, that file is failing download when I am on your branch so I think you need to merge CONP-PCNO/master on your branch to resolve that failure.
- projects/MRI_and_unbiased_averages_of_wild_muskrats__Ondatra_zibethicus__and_red_squirrels__Tamiasciurus_hudsonicus_/data_release/muskrat/demo.csv: I can download manually that dataset on the master branch of conp-dataset but the download is long as that specific file is pretty big.

**Comment by mathdugre** [comment]
@cmadjar , I  merged the branch with master and the test are fine now.

**Review by cmadjar — APPROVED** [review]

**Pull request merged**
