### PR TITLE
Add Zenodo crawler script and tests

### PR DESCRIPTION
**Pull request by joeyzhou98**
## Description
Instead of going through the complex procedure of uploading a dataset themselves, the dataset owners can now upload their dataset onto Zenodo with the keyword `canadian-open-neuroscience-platform` and this script will automatically fetch new changes and versions and create a pull request to this repository.

The procedure is as follows:
1. Make sure you have an up to date repository by pulling
2. Retrieve all current conp-dataset information stored in dats.json files (concept_doi and version_doi)
3. Retrieve all metadata for all zenodo datasets containing the keyword `canadian-open-neuroscience-platform`
4. Looping through the retrieved zenodo datasets metadata:
    1. If zenodo dataset is existing in a conp-dataset by comparing concept_doi:
        1. If the conp-dataset version is not current by comparing the zenodo dataset latest_version_doi with the conp-dataset version_doi:
            1. Update conp-dataset
    2. If the zenodo dataset doesn't exist in conp-dataset by seeing that the zenodo concept_doi is not in the concept_dois retrieved from conp-datasets
        1. Download zenodo dataset into a new dataset/directory
5. Create pull requests with changes

Here is some documentation regarding [concept_dois](http://help.zenodo.org/#versioning)

Issue #79

### CODE REVIEW

**Comment by shots47s** [comment]
So, do I just run the python script?  Are there any modules that i need to do so?

**Comment by joeyzhou98** [comment]
> So, do I just run the python script? Are there any modules that i need to do so?

Yes, you just need to run `python scripts/crawl_zenodo.py <github bot access token>`, for any modules, only `datalad` is necessary

**Comment by glatard** [comment]
Hi @joeyzhou98, great work! I'll test it more later, but one thing you could add already is detailed usage information for the script (for instance using `argparse`). The `--help` text should explain what it does, and what is the argument.

**Comment by joeyzhou98** [comment]
> Hi @joeyzhou98, great work! I'll test it more later, but one thing you could add already is detailed usage information for the script (for instance using `argparse`). The `--help` text should explain what it does, and what is the argument.

You are right, sounds like a good idea

**Comment by joeyzhou98** [comment]
Hi, @glatard please let me know if the help text is accurate and detailed enough

**Comment by glatard** [comment]
hi @Joey Zhou do you know how we could test the crawler script without creating a dataset on Zenodo that we won't be able to remove and will show up in PRs repeatedly? If not, it would be nice to add a `--sandbox` option to have the script point to Zenodo's sandbox server.

**Comment by glatard** [comment]
@shots47s or @edickie, would you like to test this script before we merge it?

**Comment by joeyzhou98** [comment]
@glatard the submodule changes are reverted and the script now checks for the token in ~/.github_token if it isn't passed by the command line and if it is, will store it in that file. Let me know if there is anything else to modify!

**Comment by shots47s** [comment]
I am a little confused at the workflow here.  So I created my own fork of conp-datasets, set up a key for it, then when I try to run this I get:

```
Zenodo query: https://zenodo.org/api/records/?type=dataset&q=keywords:"canadian-open-neuroscience-platform"
DOIs found on Zenodo: [{'concept_doi': '3478384', 'latest_version': '3478385', 'title': 'test_dataset_do_not_merge', 'files': [{'bucket': '298c97d5-5ebd-4b44-b889-ef36056d2e86', 'checksum': 'md5:d18cef89d2a2a93ff554628b078167f6', 'key': 'data.zip', 'links': {'self': 'https://zenodo.org/api/files/298c97d5-5ebd-4b44-b889-ef36056d2e86/data.zip'}, 'size': 183, 'type': 'zip'}], 'doi_badge': '10.5281/zenodo.3478384'}]
DOIs found in CONP dataset: []
[INFO   ] Creating a new annex repo at /Users/stbrown/Programs/test/conp-dataset/projects/test_dataset_do_not_merge 
.: github(-) [https://90f0a309cf94fd05394951782220710f9a99b293@github.com/shots47s/conp-dataset-test_dataset_do_not_merge.git (git)]
[INFO   ] Downloading 'https://zenodo.org/api/files/298c97d5-5ebd-4b44-b889-ef36056d2e86/data.zip' into '/Users/stbrown/Programs/test/conp-dataset/projects/test_dataset_do_not_merge' 
[INFO   ] Adding content of the archive /Users/stbrown/Programs/test/conp-dataset/projects/test_dataset_do_not_merge/data.zip into annex <AnnexRepo path=/Users/stbrown/Programs/test/conp-dataset/projects/test_dataset_do_not_merge (<class 'datalad.support.annexrepo.AnnexRepo'>)> 
[INFO   ] Initiating special remote datalad-archives 
[INFO   ] Finished adding /Users/stbrown/Programs/test/conp-dataset/projects/test_dataset_do_not_merge/data.zip: Files processed: 1, +annex: 1 
[INFO   ] Publishing <Dataset path=/Users/stbrown/Programs/test/conp-dataset/projects/test_dataset_do_not_merge> to github 
Traceback (most recent call last):                                                                          
  File "scripts/crawl_zenodo.py", line 324, in <module>
    crawl()
  File "scripts/crawl_zenodo.py", line 41, in crawl
    push_and_pull_request(commit_msg, token)
  File "scripts/crawl_zenodo.py", line 309, in push_and_pull_request
    raise Exception("Error while creating pull request: " + r.text)
Exception: Error while creating pull request: {"message":"Validation Failed","errors":[{"resource":"PullRequest","code":"custom","message":"A pull request already exists for joeyzhou98:master."}],"documentation_url":"https://developer.github.com/v3/pulls/#create-a-pull-request"}
```
So how should one start the process?

**Comment by glatard** [comment]
btw @joeyzhou98, the README file created by the script is still wrong: https://github.com/shots47s/conp-dataset-test_dataset_do_not_merge/blob/master/README.md

**Comment by glatard** [comment]
I'm a bit puzzled by the error message: `A pull request already exists for joeyzhou98:master`

**Comment by shots47s** [comment]
Well, maybe it was due to me running it in a clone of Joey’s repo.  But that is where the script is :)

I can try cloning my fork and running it there, hence my “I am confused by the work flow."
-- 
Shawn T. Brown, PhD.
Associate Director of Research Software Development  / CBRAIN Platform
McGill Centre for Integrative Neuroscience (MCIN)
McGill University
Montreal, QC, Canada
Email: stbrown@mcin.ca
Phone: 514-237-2960

**Comment by glatard** [comment]
ah, that may be the reason why the PR fails indeed.

See help text:
```
  Requirements:
    * GitHub user must have a fork of https://github.com/CONP-PCNO/conp-dataset
    * Script must be run in the base directory of a local clone of this fork
```

@joeyzhou98, do you think you could add a few safeguards to check that the requirements are met, and provide clear error messages otherwise?

**Comment by shots47s** [comment]
Well, then I shouldn't have been confused :)

**Comment by shots47s** [comment]
Ok, now I have cloned a fork of mine and tried running the tool:

```
Zenodo query: https://zenodo.org/api/records/?type=dataset&q=keywords:"canadian-open-neuroscience-platform"
DOIs found on Zenodo: [{'concept_doi': '3478384', 'latest_version': '3478385', 'title': 'test_dataset_do_not_merge', 'files': [{'bucket': '298c97d5-5ebd-4b44-b889-ef36056d2e86', 'checksum': 'md5:d18cef89d2a2a93ff554628b078167f6', 'key': 'data.zip', 'links': {'self': 'https://zenodo.org/api/files/298c97d5-5ebd-4b44-b889-ef36056d2e86/data.zip'}, 'size': 183, 'type': 'zip'}], 'doi_badge': '10.5281/zenodo.3478384'}]
DOIs found in CONP dataset: []
[INFO   ] Creating a new annex repo at /Users/stbrown/Programs/test/conp-dataset-stb/projects/test_dataset_do_not_merge 
Traceback (most recent call last):
  File "../conp-dataset/scripts/crawl_zenodo.py", line 324, in <module>
    crawl()
  File "../conp-dataset/scripts/crawl_zenodo.py", line 37, in crawl
    create_new_dataset(dataset, token)
  File "../conp-dataset/scripts/crawl_zenodo.py", line 186, in create_new_dataset
    github_passwd=token)
  File "/Users/stbrown/Programs/test/conp-dataset/venv/lib/python3.6/site-packages/datalad/distribution/dataset.py", line 527, in apply_func
    return f(**kwargs)
  File "/Users/stbrown/Programs/test/conp-dataset/venv/lib/python3.6/site-packages/datalad/distribution/create_sibling_github.py", line 200, in __call__
    existing, access_protocol, dryrun)
  File "/Users/stbrown/Programs/test/conp-dataset/venv/lib/python3.6/site-packages/datalad/support/github_.py", line 310, in _make_github_repos
    dryrun)
  File "/Users/stbrown/Programs/test/conp-dataset/venv/lib/python3.6/site-packages/datalad/support/github_.py", line 364, in _make_github_repo
    raise ValueError(msg)
ValueError: repository "conp-dataset-test_dataset_do_not_merge" already exists on Github
```
Any ideas?

**Comment by joeyzhou98** [comment]
@shots47s that is caused by the existence of the repository ‘conp-dataset-test_dataset_do_not_merge’ in your account, please delete the repository and try again

**Comment by joeyzhou98** [comment]
@glatard I am looking into why the `README.md` is still wrong

**Comment by joeyzhou98** [comment]
@glatard the README.md looks fine to me: https://github.com/joeyzhou98/conp-dataset-test_dataset_do_not_merge, maybe @shots47s, you weren't using an up-to-date version of my script

**Comment by glatard** [comment]
@shots47s did it work after you removed the existing `conp-dataset-test_dataset_do_not_merge` repo on GitHub? @joeyzhou98, maybe your code could check for this situation and either (1) exit gracefully, or (2) ask the user if they want to delete the repo (do it automatically if `--force` is used). I also had similar issues when I was testing.

**Comment by joeyzhou98** [comment]
@glatard will do

**Comment by glatard** [comment]
Hi @joeyzhou98, this looks great! I'll test it soon, but in the meantime, did you have the chance to implement the check for existing dataset repo on GitHub?

**Comment by joeyzhou98** [comment]
Hi @glatard yes it is already implemented, if you pass ’—force’ as argument and if the token has the delete repository scope checked then my script will delete the existing repo and create a new one

**Pull request merged**
