### PR TITLE
New FRDR dataset addition 

### PR DESCRIPTION
**Pull request by gi114**
## Description
This PR deals with adding a an FRDR dataset submodule to conp-dataset

## Checklist

Mandatory files and elements:
- [ ] A `README.md` file, at the root of the dataset
- [ ] A `DATS.json` file, at the root of the dataset
- [ ] If configuration is required (for instance to enable a special remote), a `config.sh` script at the root of the dataset
- [ ] A DOI (see instructions in [contribution guide](https://github.com/CONP-PCNO/conp-dataset/blob/master/.github/CONTRIBUTING.md), and corresponding badge in `README.md`

Functional checks:
- [ ] Dataset can be installed using DataLad, recursively if it has sub-datasets
- [ ] Every data file has a URL
- [ ] Every data file can be retrieved or requires authentication
- [ ] `DATS.json` is a valid DATs model
- [ ] If dataset is derived data, raw data is a sub-dataset

### CODE REVIEW

**Comment by gi114** [comment]
Hi @glatard, I will have to make some adjustments and additional tests on this dataset.  I will update the PR soon

**Comment by gi114** [comment]
Hi @glatard,

There is a config file to be executed, then try downloading

**Comment by gi114** [comment]
Hi, did anyone give a look to this one? Have you tried installing it?

**Comment by gi114** [comment]
Hi @cmadjar, there is a dependency missing, should be easy fix

**Comment by cmadjar** [comment]
@gi114 I don't see any commit since my review. I still have the same issue when I run `.config.sh`.

You branch appears to have conflicts with the base branch.

Let me know when ready for another round of testing

**Comment by gi114** [comment]
Hi @cmadjar,

There should not be any commit changes. It was a missing dependency with this module, git-annex-remote-globus. I made the update and released the new version. Which version of git annex globus remote do you have installed ? Just to understand

```pip freeze | grep git-annex-remote-globus```

Also, try to uninstall the package: ```pip uninstall git-annex-remote-globus```

and rerun the config.sh

Let me know. If successful I will still pause the PR as the config.sh does not update this package if it is already installed. 
Thanks a lot

**Comment by cmadjar** [comment]
Hi @gi114,

I removed `git-annex-remote-globus` as you suggested and rerun the `./config.sh` script and the install worked. Indeed, it would be good to modify the install so that the package is not updated if already installed.

I was able to download some of the files. I did not try them all though. The dataset seems pretty big to download...

**Comment by gi114** [comment]
@cmadjar Great !! I made a fix indeed, so the install would upgrade if the package is already installed. @glatard, let me know if that works. So I can push another FRDR dataset after this one

**Comment by glatard** [comment]
Hi @gi114, Travis and Circle failed with the same error:
```
datalad install -r .
It is highly recommended to configure Git before using DataLad. Set both 'user.name' and 'user.email' configuration variables.
It is highly recommended to configure Git before using DataLad. Set both 'user.name' and 'user.email' configuration variables.
[ERROR  ] 'gitmodule_name' [gitrepo.py:<genexpr>:2607] (KeyError) 
Exited with code exit status 1
```
I had the same error locally:
```
(datalad) [glatard@sapajou conp-dataset]$ datalad install projects/FRDR-Multimodal-2
[ERROR  ] 'gitmodule_name' [gitrepo.py:<genexpr>:2607] (KeyError)
```
It looks like there's something wrong with the dataset.

**Comment by glatard** [comment]
Also, do you know why this PR also modifies other datasets?

**Comment by gi114** [comment]
Hi @glatard,
The other dataset in .gitmodules is one that I added accidentally and removed. So that should not be a problem

In terms of the failure, did you git clone the dataset and run ```datalad install -r .``` ? I will try to replicate

**Pull request closed without merging**
