### PR TITLE
Updates in DATS schema

### PR DESCRIPTION
**Pull request by zxenia**
Updated submodule containing DATS schemas with conp custom changes to the list of the required fields.

### CODE REVIEW

**Comment by zxenia** [comment]
yes, I looked it up:
the errors are in 'hasPart' of the DATS, because 'hasPart' refers to dataset_schema (dataset can have a dataset) so it requires all the usual required fields to be present in hasPart-dataset

**Comment by zxenia** [comment]
@glatard yes sure, I will check it

**Comment by zxenia** [comment]
Hi @emmetaobrien @glatard ,

DATS validator reports errors in the following projects:

**Group 1:** these projects don't have required fields in 'hasPart' property.
'hasPart' takes a list of items, each item must follow `'dataset_schema.json#'`, therefore have all required fields for the dataset - `"required" : [ "title", "types", "creators", "licenses", "description", "keywords", "version" ]`

The datasets in 'hasPart' can just have the same values that are set for the main dataset.

- 1000GenomesProject
- Brainspan
- celltypes
- mm_neo_atlas
- nhpatlas
- refseq

**Group 2:** these projects don't have required 'licenses' and 'keywords' for the main dataset

- openpain_BrainNetworkChange_Mano
- openpain_cbp_resting
- openpain_placebo_1
- openpain_placebo_predict_tetreault
- openpain_subacute_longitudinal_study
- openpain_thermal
- BigBrain

**Comment by emmetaobrien** [comment]
I can update the Group 1 DATS.json files straightforwardly and will do so now; license data for the Group 2 projects needs external data, and selecting keywords might be better done by someone with more knowledge of the content of these datasets.

**Comment by emmetaobrien** [comment]
@zxenia @glatard Group 1 have been updated and https://github.com/CONP-PCNO/conp-dataset/pull/213 submitted.

**Comment by emmetaobrien** [comment]
@zxenia: Group 2: the openpain datasets are updated in https://github.com/CONP-PCNO/conp-dataset/pull/217.

**Comment by zxenia** [comment]
@emmetaobrien @glatard when  #217 will be merged in master, can you please restart build for this PR, I don't have access to do that.

**Comment by zxenia** [comment]
ok we are almost there :) 

One dats file is still failing:

nhpatlas in hasPart.0 is missing 'licenses', 'description', 'keywords', 'version'

@emmetaobrien can you look into it?

**Comment by emmetaobrien** [comment]
I have corrected that in https://github.com/CONP-PCNO/conp-dataset/pull/221 which should be ready to merge.

**Comment by zxenia** [comment]
Thanks @emmetaobrien ! after it's merged we need to restart the build here and it should be all good

**Pull request merged**
