### PR TITLE
fix isAbout, types and licenses according to standard

### PR DESCRIPTION
**Pull request by PapillonMcGill**
## Description
fix multiple fields according to new standard list of term

## Checklist

Mandatory files and elements:
- [ ] A `README.md` file, at the root of the dataset
- [ ] A `DATS.json` file, at the root of the dataset
- [ ] If configuration is required (for instance to enable a special remote), a `config.sh` script at the root of the dataset
- [ ] A DOI (see instructions in [contribution guide](https://github.com/CONP-PCNO/conp-dataset/blob/master/.github/CONTRIBUTING.md), and corresponding badge in `README.md`

Functional checks:
- [ ] Dataset can be installed using DataLad, recursively if it has sub-datasets
- [ ] Every data file has a URL
- [ ] Every data file can be retrieved or requires authentication
- [ ] `DATS.json` is a valid DATs model
- [ ] If dataset is derived data, raw data is a sub-dataset

## Related issues (optional)
#532 
#533
#541

### CODE REVIEW

**Review by cmadjar — CHANGES_REQUESTED** [review]
@PapillonMcGill Thank you for this. 

I noticed a few things that need to be corrected:
- There is a lot of spacing issues introduced in the DATS files.
- SIMON dataset: in `types`, there is twice the value of `MRI` but when looking at the `identifier`, the second one should be `quality control subject`, not `MRI`
- I am confused, I see that in CHBMP, `MRI` is associated to a `valueIRI` but in SIMON, it is associated to an `identifier` section. Shouldn't they refer to the same? I see this inconsistency in several of the DATS files. Sometimes `valueIRI` is used, other times `identifier` fields.
- I don't think the `identifier` section of the `celltypes` DATS for type `transcriptomics` is correctly encoded. Also, why does the `transcriptomics` term have `identifier` associated to it under `types` and `valueIRI` in `keywords`? 
- `nhpatlas` dataset: major typos in types section for `transcriptomics` ;). Also, it has `identifier` associated to it in types but `valueIRI` for keywords, why?
- `mousebytes` dataset: `hasPart` of the DATS model needs to be updated for the `privacy` and `isAbout` fields

Thanks!

**Comment by emmetaobrien** [comment]
With regard to the spacing issues, I should note that I have been consistently using tabs for indenting everywhere in DATS.json since the beginning of the project, so if @PapillonMcGill has edited files of mine using spaces for indenting that could cause oddities.

**Comment by PapillonMcGill** [comment]
spacing issue is effectively caused by space vs tab. My editor is set to use 4 space as a tab as is required in LORIS.
I can replace every 4 space with a tab if you like but to prevent issue like that in the future, i suggest to opposite. replace all tab with 4 space (some DATS files use 2 space as identation). It is also easier to control no tab vs the right amount of spaces.

"valueIRI" is required for the keywords by the schema. When using "identifier", the file didn't validated .

I will check the dataset where error where found

**Comment by cmadjar** [comment]
@PapillonMcGill there is something off with CHBMP. When I click on the diff on the frontend interface, I see no changes for that dataset.

The rest looks good. Thank you!

**Review by cmadjar — APPROVED** [review]

**Pull request merged**
