### PR TITLE
Updating openpain DATS.json files with license and keywords.

### PR DESCRIPTION
**Pull request by emmetaobrien**
This PR updates the DATS.json files for the six openpain datasets to include keywords and license information provided by @glatard.

### CODE REVIEW

**Comment by emmetaobrien** [comment]
Please do not merge yet.

**Comment by PapillonMcGill** [comment]
@emmetaobrien Travis is failing these update. Could you check?

**Comment by PapillonMcGill** [comment]
@emmetaobrien need to remove all `"valueIRI": ""`  from PreventAD-open.

**Comment by emmetaobrien** [comment]
OK, that came in via updating my fork for https://github.com/conpdatasets/preventad-open/pull/22, I will fix that separately and then this PR should no longer have problems.

**Comment by emmetaobrien** [comment]
All right, as of https://github.com/conpdatasets/preventad-open/pull/28 the Prevent-AD DATS.json passes Travis.

This update now also includes keyword and license fields in the DATS.json for BigBrain.

**Comment by PapillonMcGill** [comment]
@glatard Could you review and merge if satisfied?

**Pull request merged**
