### PR TITLE
Update to conp-dataset to refer to updated DATS.json schema

### PR DESCRIPTION
**Pull request by emmetaobrien**
This PR updates conp-dataset to point to the schema update in https://github.com/CONP-PCNO/schema/pull/2.

### CODE REVIEW

**Comment by emmetaobrien** [comment]
Gah, sorry, most if not all of that is a typo..  Fixing it now.

**Comment by emmetaobrien** [comment]
@glatard: that typo has now been fixed in https://github.com/CONP-PCNO/schema/pull/3.  If you merge that I ill update this PR accordingly.

**Comment by emmetaobrien** [comment]
I'm sorry, there's another one: https://github.com/CONP-PCNO/schema/pull/4.  Thanks to @zxenia for finding this one.

**Comment by emmetaobrien** [comment]
In order to get conp-dataset to pass all tests, I have removed several obsolete example files and updated one.  Thanks to @joeyzhou98 for very helpful assistance with navigating details of the CircleCI test output.

**Comment by emmetaobrien** [comment]
Update: conp-dataset/docs removed now that the content has been consolidated to conp-documentation in https://github.com/CONP-PCNO/conp-documentation/pull/43.

**Comment by cmadjar** [comment]
@glatard can you re-review this PR when you get a chance? Thank you!

**Comment by glatard** [comment]
LGTM too

**Pull request merged**
