### PR TITLE
BigBrain_MRISIM: [ADD] crawled dataset.

### PR DESCRIPTION
**Pull request by mathdugre**
## Description

This PR integrate one of the missing bigbrain derivatives listed in #621 .

## Checklist

Mandatory files and elements:
- [x] A `README.md` file, at the root of the dataset
- [x] A `DATS.json` file, at the root of the dataset
- [ ] If configuration is required (for instance to enable a special remote), a `config.sh` script at the root of the dataset
- [ ] A DOI (see instructions in [contribution guide](https://github.com/CONP-PCNO/conp-dataset/blob/master/.github/CONTRIBUTING.md), and corresponding badge in `README.md`

Functional checks:
- [x] Dataset can be installed using DataLad, recursively if it has sub-datasets
- [x] Every data file has a URL
- [x] Every data file can be retrieved or requires authentication
- [x] `DATS.json` is a valid DATs model
- [x] If dataset is derived data, raw data is a sub-dataset

## Related issues (optional)

#621

### CODE REVIEW

**Review by cmadjar — CHANGES_REQUESTED** [review]
@mathdugre same comments as for the other datasets:
- add bigbrain-datalad parent submodule
- check size and number of files in the DATS

**Review by cmadjar — COMMENTED** [review]
LGTM!

@emmetaobrien another one that would require your review when you have time.

**Comment by emmetaobrien** [comment]
Minor corrections to README.md.  Also, the description field in DATS.json lists the subject as 66 years old, while that age has been given as 65 in every other reference I have seen.

**Comment by cmadjar** [comment]
@emmetaobrien Thank you! Indeed, it appears to be a typo since the subject was 65 years old. Did you fix it at the same time?

**Comment by cmadjar** [comment]
@mathdugre can you update the submodule? I fixed the age in the DATS description. Note: there were conflicts in the .gitmodules that I resolved in the frontend so you might need to pull before pushing.

**Comment by mathdugre** [comment]
@cmadjar, I just updated the submodule to the latest version.

**Review by cmadjar — APPROVED** [review]

**Pull request merged**
