### PR TITLE
TravisCI test more stringent (now tests download more thoroughly)

### PR DESCRIPTION
**Pull request by joeyzhou98**
## Description
Tests now use git annex to get a list of annexed files and randomly chooses a number of them to be tested instead of recursing into the directories and using `random() < odds` to calculate when to test files

## Related issues (optional)
#170

### CODE REVIEW

**Comment by joeyzhou98** [comment]
Need to merge #179 before TravicCI can run the test properly

**Comment by joeyzhou98** [comment]
@glatard yes I am investigating this issue as behavior differs on my machine

**Comment by glatard** [comment]
Update: tests currently pass when download timeouts (after 3 secs). The timeout should be increased to 30s, and tests should fail when timeout is reached, unless authentication message is present.

**Comment by glatard** [comment]
Closing this, as this is now integrated in #197

**Pull request closed without merging**
