### PR TITLE
Adding Brainspan dataset

### PR DESCRIPTION
**Pull request by emmetaobrien**
## Description

This dataset includes 20 datalad links to repositories of zipped summary data from the BrainSpan Atlas of the Developing Human Brain, generated by the Allen Institute for Brain Science, covering developmental transcriptome data, normalised expression values for prenatal LMD microarrays, and 3-D fiber tract and developmental transcriptome sampling annotation at 8 developmental stages ranging from early embryonic to 32 years old.  It also includes a PDF of a white paper describing the normalisation process used in the developmental transcriptome dataset, and a CSV containing tissue sample metadata and URLs for downloading raw LMD microarray files.

## Checklist

Mandatory files and elements:
- [x] A `README.md` file, at the root of the dataset
- [x] A `dats.json` file, at the root of the dataset
- [x] If configuration is required (for instance to enable a special remote), a `config.sh` script at the root of the dataset
- [ ] A DOI (see instructions in [contribution guide](https://github.com/CONP-PCNO/conp-dataset/blob/master/.github/CONTRIBUTING.md), and corresponding badge in `README.md`

Functional checks:
- [ ] Dataset can be installed using DataLad, recursively if it has sub-datasets
- [ ] Every data file can be retrieved or requires authentication
- [ ] `dats.json` is a valid DATs model
- [ ] If dataset is derived data, raw data is a sub-dataset

### CODE REVIEW

**Comment by dlq** [comment]
What do I do as a reviewer with the CI checks that have failed?  Should I wait for them to pass or are these acceptable failures?

[Details](https://travis-ci.org/CONP-PCNO/conp-dataset/builds/581355512?utm_source=github_status&utm_medium=notification)

**Comment by dlq** [comment]
```
➜  conp-dataset git:(emmetaobrien-master) datalad install -r .
[INFO   ] Installing <Dataset path=/Users/dlq/Documents/GitHub/conp-dataset> recursively 
[INFO   ] Cloning https://github.com/emmetaobrien/Brainspan.git [1 other candidates] into '/Users/dlq/Documents/GitHub/conp-dataset/projects/Brainspan' 
[INFO   ]   Remote origin not usable by git-annex; setting annex-ignore                   
[INFO   ] Cloning https://github.com/emmetaobrien/nhpatlas.git [1 other candidates] into '/Users/dlq/Documents/GitHub/conp-dataset/projects/nhpatlas' 
[INFO   ]   Remote origin not usable by git-annex; setting annex-ignore                   
action summary:
  get (notneeded: 13)
  install (notneeded: 12, ok: 2)
➜  conp-dataset git:(emmetaobrien-master) git-annex version
git-annex version: 7.20190819
build flags: Assistant Webapp Pairing S3 WebDAV FsEvents TorrentParser MagicMime Feeds Testsuite
dependency versions: aws-0.21.1 bloomfilter-2.0.1.0 cryptonite-0.26 DAV-1.3.3 feed-1.2.0.0 ghc-8.6.5 http-client-0.6.4 persistent-sqlite-2.10.5 torrent-10000.1.1 uuid-1.3.13 yesod-1.6.0
key/value backends: SHA256E SHA256 SHA512E SHA512 SHA224E SHA224 SHA384E SHA384 SHA3_256E SHA3_256 SHA3_512E SHA3_512 SHA3_224E SHA3_224 SHA3_384E SHA3_384 SKEIN256E SKEIN256 SKEIN512E SKEIN512 BLAKE2B256E BLAKE2B256 BLAKE2B512E BLAKE2B512 BLAKE2B160E BLAKE2B160 BLAKE2B224E BLAKE2B224 BLAKE2B384E BLAKE2B384 BLAKE2BP512E BLAKE2BP512 BLAKE2S256E BLAKE2S256 BLAKE2S160E BLAKE2S160 BLAKE2S224E BLAKE2S224 BLAKE2SP256E BLAKE2SP256 BLAKE2SP224E BLAKE2SP224 SHA1E SHA1 MD5E MD5 WORM URL
remote types: git gcrypt p2p S3 bup directory rsync web bittorrent webdav adb tahoe glacier ddar git-lfs hook external
operating system: darwin x86_64
supported repository versions: 5 7
upgrade supported from repository versions: 0 1 2 3 4 5 6
```

**Comment by emmetaobrien** [comment]
My commits earlier today, which went in before @dlq tested and approved, were to add another new brain transcriptome dataset, the NIH Blueprint Non-Human Primate Atlas, containing transcriptome analyses of macaque cortical layers at 10 different pre- and post-natal ages, plus supporting neuroanatomical guide images as datalad links to image files.

**Comment by PapillonMcGill** [comment]
@dlq
Travis failed due to a time-out and as not marked this dataset as 'without error', so no approval yet.
I reduced the number of files Travis should pull from each dataset in order to reduce the possibility of time-out.  (We should address that with a failure to the affected dataset and continue the rest of the test if possible).

I restarted Travis to see if it will pass (at least this dataset).

**Comment by jbpoline** [comment]
I also checked the datalad get on a few files. 
@emmetaobrien : I was able to see a beautiful histology jpg image :)
All sounds good to me
@dlq : We should have a set of instructions in the Readme describing how to review a dataset, IIRC there was one but if not, could we have a first proposal ?

**Comment by emmetaobrien** [comment]
@PapillonMcGill: I have just looked at the Travis output, and the two new datasets I am adding are passing all tests correctly; the overall build failure is because of other existing datasets, which this PR does not change or affect in any way, lacking DATS.json or README.md files in my fork of conp-dataset.  I am unsure that this behaviour of Travis is optimally useful in this specific context.

**Comment by PapillonMcGill** [comment]
@emmetaobrien Yes, I know, it is not the optimal way to work, ideally we would ensure ASAP that previously merged datasets meet all the requirement. Then Travis would report the status of the new PR not existing data.

**Comment by shots47s** [comment]
We should work first then to make sure all existing datasets meet the criteria before we add new datasets.  Or alternatively, just remove the bad ones from the repository, put them in branches until they are completed.

@PapillonMcGill, can you see to this?  I think the latter is the most practical and expedient.  We should treat this like any other github repo, and master is meant to house datasets that are clean and ready to go, with merging only happening after that is true.

**Comment by shots47s** [comment]
Datalad allows us to work with branches, right? Or alternatively, we could use forks.

**Pull request merged**
