### PR TITLE
BigBrain_A3D: [ADD] crawled dataset.

### PR DESCRIPTION
**Pull request by mathdugre**
## Description

This PR integrate one of the missing bigbrain derivatives listed in #621 .

## Checklist

Mandatory files and elements:
- [x] A `README.md` file, at the root of the dataset
- [x] A `DATS.json` file, at the root of the dataset
- [ ] If configuration is required (for instance to enable a special remote), a `config.sh` script at the root of the dataset
- [ ] A DOI (see instructions in [contribution guide](https://github.com/CONP-PCNO/conp-dataset/blob/master/.github/CONTRIBUTING.md), and corresponding badge in `README.md`

Functional checks:
- [x] Dataset can be installed using DataLad, recursively if it has sub-datasets
- [x] Every data file has a URL
- [x] Every data file can be retrieved or requires authentication
- [x] `DATS.json` is a valid DATs model
- [x] If dataset is derived data, raw data is a sub-dataset

## Related issues (optional)

#621

### CODE REVIEW

**Review by cmadjar — CHANGES_REQUESTED** [review]
@mathdugre same comments as for the other BigBrain datasets:
- missing the parent submodule bigbrain-datalad
- check the size and number of files in the DATS.json file

**Review by cmadjar — COMMENTED** [review]
LGTM.

@emmetaobrien another review on this would be great as well. Thank you!

**Comment by emmetaobrien** [comment]
Again, minor edits to README.md but otherwise this looks fine to me.

**Comment by cmadjar** [comment]
Thank you @emmetaobrien !

@mathdugre could you update the BigBrain_Hippocampus_Segmentation submodule to point to its latest commit? Thanks!

**Comment by mathdugre** [comment]
@cmadjar , I update the submodule and fixed merge conflicts on my latest commit (971d802)

**Review by cmadjar — APPROVED** [review]
LGTM

**Pull request merged**
