### PR TITLE
Make OSF private dataset downloadable

### PR DESCRIPTION
**Pull request by joeyzhou98**
## Description
OSF crawled private datasets can now be accessed using `datalad get` if dataset owner gives access to user and user adds token as an environment variable under `DATALAD_OSF_token`

Documentation will be created soon at at Crawlers folder in https://github.com/CONP-PCNO/conp-documentation

## Related issues (optional)
#408

### CODE REVIEW

**Comment by cmadjar** [comment]
@joeyzhou98 @mathdugre is there a reason why Circle CI is not testing this PR? Am I missing something obvious?

**Comment by cmadjar** [comment]
@joeyzhou98 the documentation for the crawlers could go in the following directory https://github.com/CONP-PCNO/conp-documentation/tree/master/Developers-Notes/conp-dataset_crawlers

**Comment by mathdugre** [comment]
@cmadjar, I looks like Joey is following his fork with his CircleCI account.

@joeyzhou98 could you confirm if this is the case?

I had issues in the past when doing that. It can be solved by unfollowing the project than either push an empty commit or trigger the test manually.

**Comment by joeyzhou98** [comment]
> @cmadjar, I looks like Joey is following his fork with his CircleCI account.
> 
> @joeyzhou98 could you confirm if this is the case?
> 
> I had issues in the past when doing that. It can be solved by unfollowing the project than either pushing an empty commit or triggering the test manually.

Ok I unfollowed my fork with my account

**Comment by joeyzhou98** [comment]
@mathdugre we need to relax the pre-commit restrictions, it is getting ridiculous at this point since there are still so many conflicting rules and there is no way I am going to add docstrings to all these files:
```
tests/parse_results.py:1 at module level:
        D100: Missing docstring in public module
tests/parse_results.py:12 in public function `get_previous_test_results`:
        D103: Missing docstring in public function
tests/parse_results.py:30 in public function `get_test_case_output`:
        D103: Missing docstring in public function
tests/parse_results.py:60 in public function `case2datasetname`:
        D103: Missing docstring in public function
tests/parse_results.py:72 in public function `parse_test_results`:
        D103: Missing docstring in public function
scripts/data_aggregation_summary_scripts/create_data_provenance_summary.py:1 at module level:
        D100: Missing docstring in public module
scripts/data_aggregation_summary_scripts/create_data_provenance_summary.py:9 in public function `main`:
        D103: Missing docstring in public function
scripts/data_aggregation_summary_scripts/create_data_provenance_summary.py:18 in public function `parse_input`:
        D103: Missing docstring in public function
scripts/data_aggregation_summary_scripts/create_data_provenance_summary.py:64 in public function `read_conp_dataset_dir`:
        D103: Missing docstring in public function
scripts/data_aggregation_summary_scripts/create_data_provenance_summary.py:98 in public function `look_for_dats_file_in_subfolders`:
        D103: Missing docstring in public function
scripts/data_aggregation_summary_scripts/create_data_provenance_summary.py:114 in public function `parse_dats_json_file`:
        D103: Missing docstring in public function
scripts/data_aggregation_summary_scripts/create_data_provenance_summary.py:153 in public function `write_csv_file`:
        D103: Missing docstring in public function
scripts/data_aggregation_summary_scripts/create_dataset_statistcs_per_data_providers.py:1 at module level:
        D100: Missing docstring in public module
scripts/data_aggregation_summary_scripts/create_dataset_statistcs_per_data_providers.py:8 in public function `main`:
        D103: Missing docstring in public function
scripts/data_aggregation_summary_scripts/create_dataset_statistcs_per_data_providers.py:43 in public function `parse_input`:
        D202: No blank lines allowed after function docstring (found 1)
scripts/data_aggregation_summary_scripts/create_dataset_statistcs_per_data_providers.py:43 in public function `parse_input`:
        D401: First line should be in imperative mood (perhaps 'Create', not 'Creates')
scripts/data_aggregation_summary_scripts/create_dataset_statistcs_per_data_providers.py:101 in public function `parse_dats_information`:
        D202: No blank lines allowed after function docstring (found 1)
scripts/data_aggregation_summary_scripts/create_dataset_statistcs_per_data_providers.py:101 in public function `parse_dats_information`:
        D205: 1 blank line required between summary line and description (found 0)
scripts/data_aggregation_summary_scripts/create_dataset_statistcs_per_data_providers.py:101 in public function `parse_dats_information`:
        D400: First line should end with a period (not 'r')
scripts/data_aggregation_summary_scripts/create_dataset_statistcs_per_data_providers.py:143 in public function `get_stats_for_data_provider`:
        D202: No blank lines allowed after function docstring (found 1)
scripts/data_aggregation_summary_scripts/create_dataset_statistcs_per_data_providers.py:143 in public function `get_stats_for_data_provider`:
        D205: 1 blank line required between summary line and description (found 0)
scripts/data_aggregation_summary_scripts/create_dataset_statistcs_per_data_providers.py:143 in public function `get_stats_for_data_provider`:
        D400: First line should end with a period (not 'e')
scripts/data_aggregation_summary_scripts/create_dataset_statistcs_per_data_providers.py:143 in public function `get_stats_for_data_provider`:
        D401: First line should be in imperative mood (perhaps 'Produce', not 'Produces')
scripts/conp_to_nidm_terms/jsonld_generator.py:1 at module level:
        D100: Missing docstring in public module
scripts/conp_to_nidm_terms/jsonld_generator.py:9 in public function `main`:
        D103: Missing docstring in public function
scripts/conp_to_nidm_terms/jsonld_generator.py:71 in public function `help_info`:
        D103: Missing docstring in public function
tests/test_zenodo_crawler.py:1 at module level:
        D100: Missing docstring in public module
tests/test_zenodo_crawler.py:10 in public function `mock_input`:
        D103: Missing docstring in public function
tests/test_zenodo_crawler.py:17 in public function `mock_zenodo_query`:
        D103: Missing docstring in public function
tests/test_zenodo_crawler.py:57 in public function `mock_get_empty_conp_dois`:
        D103: Missing docstring in public function
tests/test_zenodo_crawler.py:61 in public function `mock_get_test_dataset_dir`:
        D103: Missing docstring in public function
tests/test_zenodo_crawler.py:65 in public class `TestZenodoCrawler`:
        D101: Missing docstring in public class
tests/test_zenodo_crawler.py:81 in public method `test_create_new_dataset`:
        D102: Missing docstring in public method
scripts/Crawlers/BaseCrawler.py:1 at module level:
        D100: Missing docstring in public module
scripts/Crawlers/BaseCrawler.py:82 in public method `get_all_dataset_description`:
        D407: Missing dashed underline after section ('Returns')
scripts/Crawlers/BaseCrawler.py:82 in public method `get_all_dataset_description`:
        D406: Section name should end with a newline ('Returns', not 'Returns:')
scripts/Crawlers/BaseCrawler.py:175 in public method `update_if_necessary`:
        D407: Missing dashed underline after section ('Returns')
scripts/Crawlers/BaseCrawler.py:175 in public method `update_if_necessary`:
        D406: Section name should end with a newline ('Returns', not 'Returns:')
scripts/Crawlers/BaseCrawler.py:205 in public method `get_readme_content`:
        D401: First line should be in imperative mood (perhaps 'Return', not 'Returns')
scripts/Crawlers/BaseCrawler.py:205 in public method `get_readme_content`:
        D407: Missing dashed underline after section ('Returns')
scripts/Crawlers/BaseCrawler.py:205 in public method `get_readme_content`:
        D406: Section name should end with a newline ('Returns', not 'Returns:')
scripts/Crawlers/BaseCrawler.py:224 in public method `run`:
        D205: 1 blank line required between summary line and description (found 0)
scripts/Crawlers/BaseCrawler.py:224 in public method `run`:
        D400: First line should end with a period (not 'D')
scripts/Crawlers/ZenodoCrawler.py:1 at module level:
        D100: Missing docstring in public module
scripts/Crawlers/ZenodoCrawler.py:31 in public class `ZenodoCrawler`:
        D101: Missing docstring in public class
scripts/Crawlers/ZenodoCrawler.py:126 in public method `get_all_dataset_description`:
        D102: Missing docstring in public method
scripts/Crawlers/ZenodoCrawler.py:308 in public method `add_new_dataset`:
        D102: Missing docstring in public method
scripts/Crawlers/ZenodoCrawler.py:339 in public method `update_if_necessary`:
        D102: Missing docstring in public method
scripts/Crawlers/ZenodoCrawler.py:399 in public method `get_readme_content`:
        D102: Missing docstring in public method
scripts/datalad_helper_scripts/batch_remove_deprecated_URLs.py:1 at module level:
        D100: Missing docstring in public module
scripts/datalad_helper_scripts/batch_remove_deprecated_URLs.py:12 in public function `parse_input`:
        D202: No blank lines allowed after function docstring (found 1)
scripts/datalad_helper_scripts/batch_remove_deprecated_URLs.py:12 in public function `parse_input`:
        D401: First line should be in imperative mood (perhaps 'Display', not 'Displays')
scripts/datalad_helper_scripts/batch_remove_deprecated_URLs.py:108 in public function `get_files_and_urls`:
        D202: No blank lines allowed after function docstring (found 1)
scripts/datalad_helper_scripts/batch_remove_deprecated_URLs.py:108 in public function `get_files_and_urls`:
        D205: 1 blank line required between summary line and description (found 0)
scripts/datalad_helper_scripts/batch_remove_deprecated_URLs.py:108 in public function `get_files_and_urls`:
        D400: First line should end with a period (not 'e')
scripts/datalad_helper_scripts/batch_remove_deprecated_URLs.py:108 in public function `get_files_and_urls`:
        D401: First line should be in imperative mood (perhaps 'Run', not 'Runs')
scripts/datalad_helper_scripts/batch_remove_deprecated_URLs.py:150 in public function `filter_invalid_urls`:
        D202: No blank lines allowed after function docstring (found 1)
scripts/datalad_helper_scripts/batch_remove_deprecated_URLs.py:150 in public function `filter_invalid_urls`:
        D205: 1 blank line required between summary line and description (found 0)
scripts/datalad_helper_scripts/batch_remove_deprecated_URLs.py:150 in public function `filter_invalid_urls`:
        D400: First line should end with a period (not 'r')
scripts/datalad_helper_scripts/batch_remove_deprecated_URLs.py:150 in public function `filter_invalid_urls`:
        D401: First line should be in imperative mood (perhaps 'Filter', not 'Filters')
scripts/datalad_helper_scripts/batch_remove_deprecated_URLs.py:175 in public function `remove_invalid_urls`:
        D202: No blank lines allowed after function docstring (found 1)
scripts/datalad_helper_scripts/batch_remove_deprecated_URLs.py:175 in public function `remove_invalid_urls`:
        D401: First line should be in imperative mood (perhaps 'Remove', not 'Removes')
scripts/dats_validator/validator.py:1 at module level:
        D100: Missing docstring in public module
scripts/dats_validator/validator.py:28 in public function `main`:
        D103: Missing docstring in public function
scripts/dats_validator/validator.py:49 in public function `validate_json`:
        D103: Missing docstring in public function
scripts/dats_validator/validator.py:78 in public function `validate_extra_properties`:
        D202: No blank lines allowed after function docstring (found 1)
scripts/dats_validator/validator.py:78 in public function `validate_extra_properties`:
        D210: No whitespaces allowed surrounding docstring text
scripts/dats_validator/validator.py:78 in public function `validate_extra_properties`:
        D401: First line should be in imperative mood (perhaps 'Check', not 'Checks')
scripts/dats_validator/validator.py:133 in public function `validate_formats`:
        D202: No blank lines allowed after function docstring (found 1)
scripts/dats_validator/validator.py:133 in public function `validate_formats`:
        D210: No whitespaces allowed surrounding docstring text
scripts/dats_validator/validator.py:133 in public function `validate_formats`:
        D401: First line should be in imperative mood (perhaps 'Check', not 'Checks')
scripts/dats_validator/validator.py:174 in public function `date_type_validation`:
        D103: Missing docstring in public function
scripts/dats_validator/validator.py:193 in public function `validate_date_types`:
        D202: No blank lines allowed after function docstring (found 1)
scripts/dats_validator/validator.py:193 in public function `validate_date_types`:
        D210: No whitespaces allowed surrounding docstring text
scripts/dats_validator/validator.py:193 in public function `validate_date_types`:
        D401: First line should be in imperative mood (perhaps 'Check', not 'Checks')
scripts/dats_validator/validator.py:217 in public function `validate_recursively`:
        D202: No blank lines allowed after function docstring (found 1)
scripts/dats_validator/validator.py:217 in public function `validate_recursively`:
        D210: No whitespaces allowed surrounding docstring text
scripts/dats_validator/validator.py:217 in public function `validate_recursively`:
        D401: First line should be in imperative mood (perhaps 'Check', not 'Checks')
scripts/dats_validator/validator.py:231 in public function `validate_non_schema_required`:
        D202: No blank lines allowed after function docstring (found 1)
scripts/dats_validator/validator.py:231 in public function `validate_non_schema_required`:
        D210: No whitespaces allowed surrounding docstring text
scripts/dats_validator/validator.py:231 in public function `validate_non_schema_required`:
        D401: First line should be in imperative mood (perhaps 'Check', not 'Checks')
scripts/dats_validator/validator.py:250 in public function `dataset_exists`:
        D202: No blank lines allowed after function docstring (found 1)
scripts/dats_validator/validator.py:250 in public function `dataset_exists`:
        D210: No whitespaces allowed surrounding docstring text
scripts/dats_validator/validator.py:250 in public function `dataset_exists`:
        D401: First line should be in imperative mood (perhaps 'Cache', not 'Caches')
scripts/dats_validator/validator.py:258 in public function `get_response_status`:
        D202: No blank lines allowed after function docstring (found 1)
scripts/dats_validator/validator.py:258 in public function `get_response_status`:
        D210: No whitespaces allowed surrounding docstring text
scripts/dats_validator/validator.py:270 in public function `help`:
        D103: Missing docstring in public function
scripts/data_aggregation_summary_scripts/lib/__init__.py:1 at module level:
        D205: 1 blank line required between summary line and description (found 0)
scripts/data_aggregation_summary_scripts/lib/__init__.py:1 at module level:
        D400: First line should end with a period (not 's')
scripts/conp_to_nidm_terms/__init__.py:1 at module level:
        D104: Missing docstring in public package
tests/test_dats_validator.py:1 at module level:
        D100: Missing docstring in public module
tests/test_dats_validator.py:23 in public class `JsonschemaTest`:
        D101: Missing docstring in public class
tests/test_dats_validator.py:24 in public method `test_validate_json`:
        D102: Missing docstring in public method
tests/test_dats_validator.py:31 in public class `ExtraPropertiesTest`:
        D101: Missing docstring in public class
tests/test_dats_validator.py:32 in public method `test_non_schema_required`:
        D102: Missing docstring in public method
tests/test_dats_validator.py:38 in public method `test_exception`:
        D102: Missing docstring in public method
tests/test_dats_validator.py:54 in public method `test_conp_status_values`:
        D102: Missing docstring in public method
tests/test_dats_validator.py:71 in public method `test_subject`:
        D102: Missing docstring in public method
scripts/Crawlers/OSFCrawler.py:1 at module level:
        D100: Missing docstring in public module
scripts/Crawlers/OSFCrawler.py:26 in public class `OSFCrawler`:
        D101: Missing docstring in public class
scripts/Crawlers/OSFCrawler.py:250 in public method `get_all_dataset_description`:
        D102: Missing docstring in public method
scripts/Crawlers/OSFCrawler.py:397 in public method `add_new_dataset`:
        D102: Missing docstring in public method
scripts/Crawlers/OSFCrawler.py:442 in public method `update_if_necessary`:
        D102: Missing docstring in public method
scripts/Crawlers/OSFCrawler.py:513 in public method `get_readme_content`:
        D102: Missing docstring in public method
scripts/data_aggregation_summary_scripts/lib/Utility.py:1 at module level:
        D100: Missing docstring in public module
scripts/data_aggregation_summary_scripts/lib/Utility.py:8 in public function `read_conp_dataset_dir`:
        D202: No blank lines allowed after function docstring (found 1)
scripts/data_aggregation_summary_scripts/lib/Utility.py:8 in public function `read_conp_dataset_dir`:
        D205: 1 blank line required between summary line and description (found 0)
scripts/data_aggregation_summary_scripts/lib/Utility.py:8 in public function `read_conp_dataset_dir`:
        D400: First line should end with a period (not 's')
scripts/data_aggregation_summary_scripts/lib/Utility.py:8 in public function `read_conp_dataset_dir`:
        D401: First line should be in imperative mood (perhaps 'Read', not 'Reads')
scripts/data_aggregation_summary_scripts/lib/Utility.py:47 in public function `read_dats_file_from_subdataset_folders`:
        D202: No blank lines allowed after function docstring (found 1)
scripts/data_aggregation_summary_scripts/lib/Utility.py:47 in public function `read_dats_file_from_subdataset_folders`:
        D401: First line should be in imperative mood (perhaps 'Read', not 'Reads')
scripts/data_aggregation_summary_scripts/lib/Utility.py:83 in public function `read_boutiques_cached_dir`:
        D202: No blank lines allowed after function docstring (found 1)
scripts/data_aggregation_summary_scripts/lib/Utility.py:83 in public function `read_boutiques_cached_dir`:
        D205: 1 blank line required between summary line and description (found 0)
scripts/data_aggregation_summary_scripts/lib/Utility.py:83 in public function `read_boutiques_cached_dir`:
        D400: First line should end with a period (not 's')
scripts/data_aggregation_summary_scripts/lib/Utility.py:83 in public function `read_boutiques_cached_dir`:
        D401: First line should be in imperative mood (perhaps 'Read', not 'Reads')
scripts/data_aggregation_summary_scripts/lib/Utility.py:111 in public function `write_csv_file`:
        D202: No blank lines allowed after function docstring (found 1)
scripts/data_aggregation_summary_scripts/lib/Utility.py:111 in public function `write_csv_file`:
        D205: 1 blank line required between summary line and description (found 0)
scripts/data_aggregation_summary_scripts/lib/Utility.py:111 in public function `write_csv_file`:
        D400: First line should end with a period (not ':')
scripts/datalad_crawlers/BigBrain_crawler.py:1 at module level:
        D100: Missing docstring in public module
scripts/datalad_crawlers/BigBrain_crawler.py:10 in public function `crawl`:
        D200: One-line docstring should fit on one line with quotes (found 3)
scripts/datalad_crawlers/BigBrain_crawler.py:10 in public function `crawl`:
        D400: First line should end with a period (not 'x')
scripts/conp_to_nidm_terms/functions.py:1 at module level:
        D100: Missing docstring in public module
scripts/conp_to_nidm_terms/functions.py:32 in public function `get_api_response`:
        D202: No blank lines allowed after function docstring (found 1)
scripts/conp_to_nidm_terms/functions.py:32 in public function `get_api_response`:
        D205: 1 blank line required between summary line and description (found 0)
scripts/conp_to_nidm_terms/functions.py:76 in public function `collect_values`:
        D202: No blank lines allowed after function docstring (found 1)
scripts/conp_to_nidm_terms/functions.py:76 in public function `collect_values`:
        D205: 1 blank line required between summary line and description (found 0)
scripts/conp_to_nidm_terms/functions.py:76 in public function `collect_values`:
        D401: First line should be in imperative mood (perhaps 'Iterate', not 'Iterates')
scripts/conp_to_nidm_terms/functions.py:165 in public function `find_duplicates`:
        D205: 1 blank line required between summary line and description (found 0)
scripts/conp_to_nidm_terms/functions.py:165 in public function `find_duplicates`:
        D400: First line should end with a period (not ')')
scripts/conp_to_nidm_terms/functions.py:165 in public function `find_duplicates`:
        D401: First line should be in imperative mood (perhaps 'Find', not 'Finds')
scripts/conp_to_nidm_terms/functions.py:191 in public function `generate_jsonld_files`:
        D205: 1 blank line required between summary line and description (found 0)
scripts/conp_to_nidm_terms/functions.py:191 in public function `generate_jsonld_files`:
        D401: First line should be in imperative mood (perhaps 'Generate', not 'Generates')
scripts/unlock.py:1 at module level:
        D100: Missing docstring in public module
scripts/unlock.py:37 in public function `unlock`:
        D103: Missing docstring in public function
scripts/crawl.py:1 at module level:
        D100: Missing docstring in public module
scripts/crawl.py:10 in public function `parse_args`:
        D103: Missing docstring in public function
tests/test_osf_crawler.py:1 at module level:
        D100: Missing docstring in public module
tests/test_osf_crawler.py:7 in public class `TestOSFCrawler`:
        D101: Missing docstring in public class
tests/test_osf_crawler.py:23 in public method `test_create_new_dataset`:
        D102: Missing docstring in public method
tests/functions.py:1 at module level:
        D100: Missing docstring in public module
tests/functions.py:19 in public function `timeout`:
        D103: Missing docstring in public function
tests/functions.py:133 in public function `generate_datalad_provider`:
        D103: Missing docstring in public function
tests/functions.py:193 in public function `eval_config`:
        D103: Missing docstring in public function
tests/functions.py:199 in public function `authenticate`:
        D103: Missing docstring in public function
tests/functions.py:230 in public function `get_filenames`:
        D103: Missing docstring in public function
tests/functions.py:267 in public function `download_files`:
        D103: Missing docstring in public function
tests/functions.py:307 in public function `get_approx_ksmallests`:
        D103: Missing docstring in public function
tests/functions.py:369 in public function `get_sample_files_size`:
        D103: Missing docstring in public function
tests/template.py:1 at module level:
        D200: One-line docstring should fit on one line with quotes (found 2)
tests/template.py:24 in public function `delay_rerun`:
        D103: Missing docstring in public function
tests/template.py:32 in public class `Template`:
        D101: Missing docstring in public class
tests/template.py:34 in public method `install_dataset`:
        D102: Missing docstring in public method
tests/template.py:41 in public method `test_has_readme`:
        D102: Missing docstring in public method
tests/template.py:48 in public method `test_has_valid_dats`:
        D102: Missing docstring in public method
tests/template.py:99 in public method `test_download`:
        D102: Missing docstring in public method
tests/template.py:118 in public method `test_files_integrity`:
        D102: Missing docstring in public method
scripts/conp_to_nidm_terms/report_generator.py:1 at module level:
        D100: Missing docstring in public module
scripts/conp_to_nidm_terms/report_generator.py:10 in public function `main`:
        D103: Missing docstring in public function
scripts/conp_to_nidm_terms/report_generator.py:77 in public function `help_info`:
        D103: Missing docstring in public function
tests/create_tests.py:1 at module level:
        D100: Missing docstring in public module
tests/create_tests.py:10 in public function `get_datasets`:
        D103: Missing docstring in public function
scripts/dats_validator/__init__.py:1 at module level:
        D104: Missing docstring in public package
tests/__init__.py:1 at module level:
        D104: Missing docstring in public package
```

**Comment by cmadjar** [comment]
@joeyzhou98 I think if you merge conp/master into your branch, that would resolve the lint issues.

Let me know when this is ready for final review. I quickly looked at the code already and it makes sense. I like the new 'no-pr' option :)

**Comment by joeyzhou98** [comment]
@cmadjar Indeed it seems like it's all fixed, ready for a final review

**Review by cmadjar — APPROVED** [review]
LGTM. Thank you @joeyzhou98 !

**Pull request merged**
