### PR TITLE
Add PERFORM dataset

### PR DESCRIPTION
**Pull request by thomasbeaudry**

### CODE REVIEW

**Comment by paiva** [comment]
I think you need to edit the `.gitmodules` file with the following information:

```
[submodule "projects/PERFORM"]
	path = projects/PERFORM
	url = https://github.com/thomasbeaudry/conp-dataset-PERFORM.git
```

@PapillonMcGill is this correct?

**Comment by PapillonMcGill** [comment]
Yes, as commented by @paiva, this would create a sub dataset. Adding your UUID to a log file will not help much.

**Comment by paiva** [comment]
@thomasbeaudry I think you should open a different PR and compare master branch with master branch (instead of git-annex with git-annex). Do you agree @PapillonMcGill ?

**Comment by glatard** [comment]
Hi @thomasbeaudry, thank you so much for this!

Indeed, the PR should be from your `master` branch to `master`.

I can also see that the files have 2 URLs:
```
$ git annex whereis loris_913174_V1_fMRI_005.mnc
whereis loris_913174_V1_fMRI_005.mnc (2 copies) 
  	58487f3c-f9c7-4624-9237-75c6e4320d53 -- tmtg@tbeaudry:~/conp-dataset/projects/PERFORM
   	cf13d535-b47c-5df6-8590-0793cb08a90a -- [datalad]

  datalad: http://perform-wiki.concordia.ca/loris/loris_913174_V1_fMRI_005.mnc
  datalad: https://loris.concordia.ca/api/v0.0.3-dev/candidates/913174/V1/images/loris_913174_V1_fMRI_005.mnc
```
It is intentional?

Also, port 80 of `loris.concordia.ca` seems to be accessible from outside the Concordia network (with auth of course), is it normal?

**Comment by thomasbeaudry** [comment]
Okay, i did master to master, PR #25   No port 80 should be closed,  I will inform the netwoking team.  @glatard I wasn't aware that there are 2 urls.  I wanted to use perform-wiki to dump the files on to since it doesn't require auth (only vpn access)

**Pull request closed without merging**
