### PR TITLE
fix licenses according to standard

### PR DESCRIPTION
**Pull request by PapillonMcGill**
## Description
fix licenses field according to new standard
added identifier when available

## Checklist

Mandatory files and elements:
- [ ] A `README.md` file, at the root of the dataset
- [ ] A `DATS.json` file, at the root of the dataset
- [ ] If configuration is required (for instance to enable a special remote), a `config.sh` script at the root of the dataset
- [ ] A DOI (see instructions in [contribution guide](https://github.com/CONP-PCNO/conp-dataset/blob/master/.github/CONTRIBUTING.md), and corresponding badge in `README.md`

Functional checks:
- [ ] Dataset can be installed using DataLad, recursively if it has sub-datasets
- [ ] Every data file has a URL
- [ ] Every data file can be retrieved or requires authentication
- [ ] `DATS.json` is a valid DATs model
- [ ] If dataset is derived data, raw data is a sub-dataset

## Related issues (optional)
#540

### CODE REVIEW

**Comment by cmadjar** [comment]
@PapillonMcGill conflicts with the base branch.

The Circle CI error is due to the fact that the 1000GenomesProject does not include the latest change from Emmet in https://github.com/CONP-PCNO/conp-dataset/pull/558

**Comment by cmadjar** [comment]
@PapillonMcGill there are still conflicts with the master branch

**Review by cmadjar — CHANGES_REQUESTED** [review]
@PapillonMcGill In visual-working-memory, there is a typo in the license name (extra closing bracket that should not be there).

For the identifier field, I am noting that some of the licenses do not have identifier. Is that correct? Example CC BY-NC-SA

Finally, the indentation of the text in the change appears to be off for several datasets. Might be worth fixing those. Look at the github diff and you will see which datasets have an odd indentation in the license field of the DATS files.

Thank you!

**Comment by PapillonMcGill** [comment]
@cmadjar For the identifier fields that are empty, it is because there is still no NIDM (or other) entry, waiting for Kzenia request to be approved.

Identation is due to the presence of `tab` in the text. I only used space and everything was fine inside my editor.
Do I replace all tab by 4 (or 2) spaces in those files. We should have a rule about no tab, this would prevent confusion.

**Pull request closed without merging**
