### PR TITLE
Added CHBMP dataset as a submodule

### PR DESCRIPTION
**Pull request by cmadjar**
## Description

This adds the Cuban Human Brain Mapping Project (CHBMP) to the CONP super dataset.

Note: the subproject CHBMP has no data yet in the repository, just descriptions of the dataset

## Checklist

Mandatory files and elements:
- [x] A `README.md` file, at the root of the dataset
- [x] A `DATS.json` file, at the root of the dataset
- [ ] If configuration is required (for instance to enable a special remote), a `config.sh` script at the root of the dataset
- [x] A DOI (see instructions in [contribution guide](https://github.com/CONP-PCNO/conp-dataset/blob/master/.github/CONTRIBUTING.md), and corresponding badge in `README.md`

Functional checks:
- [ ] Dataset can be installed using DataLad, recursively if it has sub-datasets
- [ ] Every data file has a URL
- [ ] Every data file can be retrieved or requires authentication
- [ ] `DATS.json` is a valid DATs model
- [ ] If dataset is derived data, raw data is a sub-dataset

## Related issues (optional)
Resubmitted https://github.com/CONP-PCNO/conp-dataset/pull/369

### CODE REVIEW

**Comment by cmadjar** [comment]
@joeyzhou98 I am not sure I understand this error either. At least, it is not the same so progress :).

Let me know what I am missing. Thanks!

**Comment by joeyzhou98** [comment]
@cmadjar it seems like we have an internal problem with the testing suite, I will let you know when this is resolved

**Comment by glatard** [comment]
Tests are now fixed, following #379, let's see if this now passes.

**Comment by glatard** [comment]
DATS file seems to be invalid.

**Comment by cmadjar** [comment]
I wonder if this is because we added the origin institution to the schema and this is not validated? This is the only thing that changed in the last commit of the DATS file. 
@emmetaobrien thoughts?

**Comment by zxenia** [comment]
@cmadjar yes, it is because of how the origin is modeled - I added a comment [here ](https://github.com/CONP-PCNO/conp-dataset/issues/370#issuecomment-666752062)

**Comment by cmadjar** [comment]
@emmetaobrien ready for your review. Thanks!

**Pull request merged**
