### PR TITLE
[Update] Update the submodules with the descriptor files

### PR DESCRIPTION
**Pull request by paiva**
This updates contain the new descriptor files for multicenter-phantom and prevent-ad

### CODE REVIEW

**Comment by paiva** [comment]
The .gitmodules didn't update correctly.

**Comment by jbpoline** [comment]
Is there an error message / some ways of documenting the problem ?

**Comment by paiva** [comment]
It is because it is not pointing to `master`
Screen Shot 2019-04-26 at 7 56 36 PM

**Comment by jbpoline** [comment]
I tested: 
```
(py3) git clone git@github.com:conpdatasets/conp-dataset.git
(py3) cd conp-dataset/
(py3) datalad install -r .
(py3) cd projects/multicenter-phantom/
(py3) t-jb:~/data/conp/tmp/conp-dataset/projects/multicenter-phantom
git[master] $ git annex whereis phantom_999876_MNI_20091020_t1w_002.mnc
whereis phantom_999876_MNI_20091020_t1w_002.mnc (1 copy) 
  	cf13d535-b47c-5df6-8590-0793cb08a90a -- [datalad]

  datalad: https://phantom-dev.loris.ca/api/v0.0.3-dev/candidates/999876/MNI_20091020/images/phantom_999876_MNI_20091020_t1w_002.mnc
ok
```
So that looks ok at least for that repo ? how do find out that there is a pb ?

**Pull request merged**
