### PR TITLE
Updating DATS.json with extra fields, logos

### PR DESCRIPTION
**Pull request by emmetaobrien**
## Description

This PR includes updates standardising and adding to DATS.json files for 10 datasets (1000GenomesProject, Brainspan, celltypes, mm_neo_atlas, multicenter-phantom, nhpatlas, preventad-open, refseq, and visual-working-memory), with the intent of making more summary data for the dataset readily available to the CONP portal

The additions take the following format:

"distributions": [
	        {
			"formats": [
				"vcf",
				"FASTA"
            		],
			"size" : 1,
		        "unit" : {
            			"value": "GB"
		        },
			"access": {
				"landingPage": "https://www.internationalgenome.org/"
			}
		}
	],

adding formats of datafiles contained, overall dataset size in GB, and a landing page for access to the external source of the data;

and

"extraProperties": [
		{
			"category": "contact",
			"values": [
				{
					"value": "Jennifer Tremblay-Mercier, Research Co-ordinator, jennifer.tremblay-mercier@douglas.mcgill.ca, 514-761-6131 #3329"
				}
			]
		},
		{
			"category": "files",
			"values": [
				{
					"value": "25"
				}
			]
		},
		{
			"category": "subjects",
			"values": [
				{
					"value": "2504"
				}
			]
		},
		{
			"category": "logo",
			"values": [
				{
					"value": "logo.png"
				}
			]
		}
	]

adding total number of files, number of subjects if applicable, and a link to a logo where applicable.

Number of subjects was not generated for the 2 non-human datasets (mm_neo_atlas and nhpatlas) or the reference genome dataset (refseq) and refers only to human subjects in the celltypes dataset.

This PR also adds logo files in the root of 9 of these datasets, with the standard name logo.png, derived from the portal mockup at portal.conp.io or the homepage of the dataset as appropriate.  The exception is the mm_neo_atlas dataset, which is supplementary material for a Nature paper and has no specific associated logo.

The structure of these additions was chosen to maintain compatibility, as far as possible, with datasets which already contained some of this information.

### CODE REVIEW

**Comment by xlecours** [comment]
I think this is a good move toward standardization of DATS files specifically used by the conp-portal.
On a side note, do you think that having a "fork" of https://w3id.org/dats/schema/dataset_schema.json in which, we would add required fields and adapt the description of the properties to explain their usage on the portal, would be the next step?
I'am thinking that this version of the dataset_schema could be used by the yet-to-be-validator run by travis.

**Comment by emmetaobrien** [comment]
I've been modifying my validation perl script for checking what I have been doing this last couple of days, but forking the dataset schema sounds like a more powerful and flexible solution to me.

**Comment by emmetaobrien** [comment]
I have submitted PRs equivalent to this one - mostly the same plus correcting some minor errors - on the three Khan lab datasets linked in conp-dataset/projects, which I do not have access to modify directly.

**Comment by emmetaobrien** [comment]
The additional update this morning was to correct a number of typos in description text for the PreventAD dataset, which have no effect on the functionality of the modifications.

**Pull request merged**
