### PR TITLE
[Dataset] Add Samir phantom dataset

### PR DESCRIPTION
**Pull request by paiva**
This PR:
* Adds Samir Phantom dataset (multicenter-dataset) from the CONPDatasets repo (https://github.com/conpdatasets/multicenter-phantom)

### CODE REVIEW

**Comment by paiva** [comment]
@jbpoline this is where the DATS file is located: https://github.com/conpdatasets/multicenter-phantom/blob/master/.datalad/metadata/aggregate_v1.json.DATS

**Comment by jbpoline** [comment]
Question: do we want the final clean dataset to be on 
* https://github.com/CONP-PCNO/conp-dataset/
or
* https://github.com/conpdatasets/
?

When trying to `datalad install -r https://github.com/conpdatasets` I get some errors. Has the dataset been properly published on github ? I am investigating now what is wrong with the dataset. 

* For the DATS model: the DATS.json file should probably part of the dataset (but not sure it is there). How was the aggregate_v1.json.DATS created? 


[ERROR  ] Failed to clone from any candidate source URL. Encountered errors per each url were: (OrderedDict([('https://github.com/conpdatasets', "Cmd('/usr/lib/git-annex.linux/git') failed due to: exit code(128)\n  cmdline: /usr/lib/git-annex.linux/git clone --progress -v https://github.com/conpdatasets /home/jb/data/conp-tmp/conpdatasets [cmd.py:wait:418]"), ('https://github.com/conpdatasets/.git', "Cmd('/usr/lib/git-annex.linux/git') failed due to: exit code(128)\n  cmdline: /usr/lib/git-annex.linux/git clone --progress -v https://github.com/conpdatasets/.git /home/jb/data/conp-tmp/conpdatasets [cmd.py:wait:418]")]),) [install(/home/jb/data/conp-tmp/conpdatasets)] 
install(error): /home/jb/data/conp-tmp/conpdatasets (dataset) [Failed to clone from any candidate source URL. Encountered errors per each url were: (OrderedDict([('https://github.com/conpdatasets', "Cmd('/usr/lib/git-annex.linux/git') failed due to: exit code(128)\n  cmdline: /usr/lib/git-annex.linux/git clone --progress -v https://github.com/conpdatasets /home/jb/data/conp-tmp/conpdatasets [cmd.py:wait:418]"), ('https://github.com/conpdatasets/.git', "Cmd('/usr/lib/git-annex.linux/git') failed due to: exit code(128)\n  cmdline: /usr/lib/git-annex.linux/git clone --progress -v https://github.com/conpdatasets/.git /home/jb/data/conp-tmp/conpdatasets [cmd.py:wait:418]")]),)]
[WARNING] path not associated with any dataset [get(/home/jb/data/conp-tmp/conpdatasets)] 
action summary:
  get (impossible: 1)
  install (error: 1)

**Comment by paiva** [comment]
I don't think your command `datalad install -r https://github.com/conpdatasets` works. 

For instance, for OpenNeuroDatasets, it also fails:
```
datalad install -r https://github.com/openneurodatasets      Sat Apr 20 13:59:12 2019
[INFO   ] Cloning https://github.com/openneurodatasets [1 other candidates] into '/Users/s/Work/MNI/CONP/data/openneurodatasets'
Username for 'https://github.com': paiva
Password for 'https://paiva@github.com':
[ERROR  ] Failed to clone from any candidate source URL. Encountered errors per each url were: (OrderedDict([('https://github.com/openneurodatasets', "Cmd('git') failed due to: exit code(128)\n  cmdline: git clone --progress -v https://github.com/openneurodatasets /Users/s/Work/MNI/CONP/data/openneurodatasets [cmd.py:wait:415]"), ('https://github.com/openneurodatasets/.git', "Cmd('git') failed due to: exit code(128)\n  cmdline: git clone --progress -v https://github.com/openneurodatasets/.git /Users/s/Work/MNI/CONP/data/openneurodatasets [cmd.py:wait:415]")]),) [install(/Users/s/Work/MNI/CONP/data/openneurodatasets)]
install(error): /Users/s/Work/MNI/CONP/data/openneurodatasets (dataset) [Failed to clone from any candidate source URL. Encountered errors per each url were: (OrderedDict([('https://github.com/openneurodatasets', "Cmd('git') failed due to: exit code(128)\n  cmdline: git clone --progress -v https://github.com/openneurodatasets /Users/s/Work/MNI/CONP/data/openneurodatasets [cmd.py:wait:415]"), ('https://github.com/openneurodatasets/.git', "Cmd('git') failed due to: exit code(128)\n  cmdline: git clone --progress -v https://github.com/openneurodatasets/.git /Users/s/Work/MNI/CONP/data/openneurodatasets [cmd.py:wait:415]")]),)]
[WARNING] path not part of the reference dataset at /Users/s/Work/MNI/CONP/data/openneurodatasets [get(/Users/s/Work/MNI/CONP/data/openneurodatasets)]
action summary:
  get (impossible: 1)
  install (error: 1)
```
If you run `datalad install https://github.com/conpdatasets/multicenter-phantom.git`, works for a single dataset.

**Comment by paiva** [comment]
Opened new PR: https://github.com/CONP-PCNO/conp-dataset/pull/30

**Pull request closed without merging**
