### PR TITLE
BigBrain_Hippocampus_Segmentation: [ADD] crawled dataset.

### PR DESCRIPTION
**Pull request by mathdugre**
## Description

This PR integrate one of the missing bigbrain derivatives listed in #621 .

## Checklist

Mandatory files and elements:
- [x] A `README.md` file, at the root of the dataset
- [x] A `DATS.json` file, at the root of the dataset
- [ ] If configuration is required (for instance to enable a special remote), a `config.sh` script at the root of the dataset
- [ ] A DOI (see instructions in [contribution guide](https://github.com/CONP-PCNO/conp-dataset/blob/master/.github/CONTRIBUTING.md), and corresponding badge in `README.md`

Functional checks:
- [x] Dataset can be installed using DataLad, recursively if it has sub-datasets
- [x] Every data file has a URL
- [x] Every data file can be retrieved or requires authentication
- [x] `DATS.json` is a valid DATs model
- [x] If dataset is derived data, raw data is a sub-dataset

## Related issues (optional)

#621

### CODE REVIEW

**Review by cmadjar — CHANGES_REQUESTED** [review]
@mathdugre same comment as the other datasets:
- missing the bigbrain-datalad submodule
- please check values in the DATS file for size and number of files

**Review by cmadjar — COMMENTED** [review]
This looks good to me.

@emmetaobrien another eye on the dataset as well as the DATS and README contents would be great if you have time. Thank you!

**Comment by emmetaobrien** [comment]
I have made some minor edits to README.md, other than that this looks fine.

**Comment by cmadjar** [comment]
Thank you @emmetaobrien !

@mathdugre could you update the BigBrain_Hippocampus_Segmentation submodule to point to its latest commit? Thanks!

**Review by cmadjar — APPROVED** [review]
LGTM

**Pull request merged**
