### PR TITLE
Update projects/1000GenomesProject to most recent version

### PR DESCRIPTION
**Pull request by emmetaobrien**
Updates 1000GenomesProject for https://github.com/conpdatasets/1000GenomesProject/pull/14

### CODE REVIEW

**Review by cmadjar — COMMENTED** [review]
@emmetaobrien why is there so many files changed? I was expecting to see only the 1000GenomesProject

**Comment by emmetaobrien** [comment]
That was an error, those are other changes from other not yet accepted PRs. I will try to clean that up this afternoon.

**Comment by cmadjar** [comment]
@emmetaobrien I still see changes to unrelated submodules in this PR. There should only be updates to the 1000GenomesProject submodule in that PR. Thanks!

**Comment by surchs** [comment]
@emmetaobrien: the fails here are a result of the updated context submodules. There is a context fixture in the annotator test that  needs to be updated for the extended DATS contexts. This should however happen in a separate PR, I'll open an issue and fix this!

I agree with @cmadjar here: roll-back all changes that are not related to `Update projects/1000GenomesProject to most recent version` and then let's deal with the rest separately. That will also resolve the failing test for this PR.

**Review by cmadjar — APPROVED** [review]

**Pull request merged**
