### PR TITLE
Add URI format validation

### PR DESCRIPTION
**Pull request by zxenia**
## Description
The PR adds URI format validation to dats validator script.

**Example:** distribution->access->landingPage has a type `string` and format set to `uri`.
If the provided URI  is not of a valid format it will throw an error.

**Important:** e.g. `www.internationalgenome.org` is not a valid URI.
URI must start with a naming schema (e.g.: `http:`, `urn:`, `mailto:` etc.).

### CODE REVIEW

**Comment by zxenia** [comment]
Tests fail:

`Dataset projects/Expression_based_polygenic_score_from_the_amygdala_5HTT_gene_network doesn't contain a valid DATS.json.`

I checked this projects' DATS file it contains text in `landingPage`  field:

`"landingPage":	"Not defined yet"`

**Comment by cmadjar** [comment]
@emmetaobrien The EPRs dataset will be failing tests because they do not provide a proper URL for the landing page field. Could this be fixed or be left out of the DATS file?

**Review by cmadjar — APPROVED** [review]

**Comment by emmetaobrien** [comment]
I have talked to the people who provided the EPR dataset about this and they have not given us a URL they are happy to include here, but our current validator requires that this field be filled.  I think before we make a decision what to do here we need to make a policy decision, and I will put that on the agenda for tomorrow morning's CONP dev meeting.

**Comment by zxenia** [comment]
@cmadjar For this PR the problem was the EPR dataset. I think we agreed to add the github repo as a landing page (now it has a string 'Not defined yet').

**Comment by cmadjar** [comment]
right. @emmetaobrien do you have any news from the EPR people? If they still don't have a landingPage, could we update the DATS file and use the dataset github repo? Thanks!

**Comment by emmetaobrien** [comment]
I have had nothing back from them, so yes, doing this now.

**Comment by emmetaobrien** [comment]
As this dataset was generated by conp-bot, it is not possible to manually update it.  I will contact the dataset providers and ask them to update it at their end.

**Comment by zxenia** [comment]
Thank you @emmetaobrien

**Comment by emmetaobrien** [comment]
Once https://github.com/CONP-PCNO/conp-dataset/pull/487 is merged there will no longer be an issue with the EPRs dataset.

**Pull request merged**
