### PR TITLE
Fix linting issue reported

### PR DESCRIPTION
**Pull request by mathdugre**
## Description

This PR aims to standardize the code style of the repository.
It solves the issues reported by the GitHub *linting* workflow .

## Currently addressed hooks

- [x] check-added-large-files
- [x] check-ast
- [x] check-json
- [x] check-merge-conflict
- [x] check-yaml
- [x] debug-statements
- [x] end-of-file-fixer
- [x] check-executables-have-shebangs
- [ ] mypy
- [x] pyupgrade
- [x] check-builtin-literals
- [x] check-docstring-first
- [x] pretty-format-json
- [x] trailing-whitespace
- [x] add-trailing-comma
- [x] black
- [x] blacken-docs
- [x] dockerfilelint
- [x] flake8
- [ ] pydocstyle
- [x] reorder-python-imports

### CODE REVIEW

**Comment by cmadjar** [comment]
@mathdugre failing Circle CI

Screen Shot 2021-04-08 at 10 35 15 AM

**Comment by mathdugre** [comment]
@cmadjar, this test pass in my local docker image for testing and the failure message is not really descriptive. We might want to rerun the test suite for the PR before spending time debugging the issues.

**Comment by cmadjar** [comment]
@mathdugre sorry, I thought I did but very possible I did not, LOL. Restarted now. Let's wait and see :-)

**Comment by cmadjar** [comment]
@mathdugre OK, The build and test worked but this is failing the linting step. Looks like mypy and flake8 is failing as far as I can tell.

**Comment by cmadjar** [comment]
@mathdugre Issues are the following if I did not miss any.

I see that in the description above, mypy, pydocstring and flake8 are not checked. Is the plan to correct them in a separate PR? About about the `check-builtin-literals`? This one also fails as you can see below.

Hope this helps. Let me know.

```
mypy.....................................................................Failed
- hook id: mypy
- exit code: 2

tests/functions.py:179: error: syntax error in type comment
tests/functions.py:328: error: syntax error in type comment
Found 2 errors in 1 file (checked 27 source files)
```

```
Check builtin type constructor use.......................................Failed
- hook id: check-builtin-literals
- exit code: 1

scripts/dats_validator/validator.py:246:8: replace dict() with {}
scripts/conp_to_nidm_terms/functions.py:144:13: replace dict() with {}
scripts/conp_to_nidm_terms/functions.py:170:13: replace list() with []
scripts/conp_to_nidm_terms/functions.py:174:31: replace dict() with {}
tests/functions.py:238:14: replace list() with []
tests/functions.py:247:25: replace list() with []
tests/functions.py:248:28: replace list() with []
```

And 

```
flake8...................................................................Failed
- hook id: flake8
- exit code: 1

tests/parse_results.py:67:9: W503 line break before binary operator
tests/parse_results.py:68:9: W503 line break before binary operator
scripts/data_aggregation_summary_scripts/create_data_provenance_summary.py:56:13: W503 line break before binary operator
scripts/data_aggregation_summary_scripts/create_data_provenance_summary.py:134:21: W503 line break before binary operator
scripts/data_aggregation_summary_scripts/create_dataset_statistcs_per_data_providers.py:92:13: W503 line break before binary operator
scripts/Crawlers/ZenodoCrawler.py:90:31: B007 Loop control variable 'dirs' not used within the loop body. If this is intended, start the name with an underscore.
scripts/Crawlers/ZenodoCrawler.py:320:13: W503 line break before binary operator
scripts/Crawlers/ZenodoCrawler.py:323:13: W503 line break before binary operator
scripts/Crawlers/ZenodoCrawler.py:378:17: W503 line break before binary operator
scripts/Crawlers/ZenodoCrawler.py:381:17: W503 line break before binary operator
scripts/dats_validator/validator.py:151:21: W503 line break before binary operator
tests/test_dats_validator.py:8:1: E402 module level import not at top of file
tests/test_dats_validator.py:48:9: B017 assertRaises(Exception): should be considered evil. It can lead to your test passing even if the code being tested is never executed due to a typo. Either assert for a more specific exception (builtin or custom), use assertRaisesRegex, or use the context manager form of assertRaises.
tests/test_dats_validator.py:56:9: B017 assertRaises(Exception): should be considered evil. It can lead to your test passing even if the code being tested is never executed due to a typo. Either assert for a more specific exception (builtin or custom), use assertRaisesRegex, or use the context manager form of assertRaises.
scripts/Crawlers/OSFCrawler.py:65:13: W503 line break before binary operator
scripts/data_aggregation_summary_scripts/lib/Utility.py:127:9: W503 line break before binary operator
scripts/data_aggregation_summary_scripts/lib/Utility.py:128:9: W503 line break before binary operator
scripts/data_aggregation_summary_scripts/lib/Utility.py:129:9: W503 line break before binary operator
scripts/data_aggregation_summary_scripts/lib/Utility.py:130:9: W503 line break before binary operator
scripts/data_aggregation_summary_scripts/lib/Utility.py:131:9: W503 line break before binary operator
scripts/conp_to_nidm_terms/functions.py:94:15: B007 Loop control variable 'directories' not used within the loop body. If this is intended, start the name with an underscore.
scripts/conp_to_nidm_terms/functions.py:184:21: B007 Loop control variable 'k' not used within the loop body. If this is intended, start the name with an underscore.
scripts/unlock.py:62:9: W503 line break before binary operator
scripts/unlock.py:71:27: B007 Loop control variable 'dirs' not used within the loop body. If this is intended, start the name with an underscore.
scripts/crawl.py:102:17: W503 line break before binary operator
scripts/crawl.py:110:17: W503 line break before binary operator
scripts/crawl.py:111:17: W503 line break before binary operator
scripts/data_aggregation_summary_scripts/create_tools_statistics_per_domain.py:71:9: W503 line break before binary operator
scripts/data_aggregation_summary_scripts/create_tools_statistics_per_domain.py:72:9: W503 line break before binary operator
scripts/data_aggregation_summary_scripts/create_tools_statistics_per_domain.py:184:13: W503 line break before binary operator
```

```
pydocstyle...............................................................Failed
- hook id: pydocstyle
- exit code: 1

tests/parse_results.py:1 at module level:
        D100: Missing docstring in public module
tests/parse_results.py:12 in public function `get_previous_test_results`:
        D103: Missing docstring in public function
tests/parse_results.py:30 in public function `get_test_case_output`:
        D103: Missing docstring in public function
tests/parse_results.py:60 in public function `case2datasetname`:
        D103: Missing docstring in public function
tests/parse_results.py:72 in public function `parse_test_results`:
        D103: Missing docstring in public function
scripts/data_aggregation_summary_scripts/create_data_provenance_summary.py:1 at module level:
        D100: Missing docstring in public module
scripts/data_aggregation_summary_scripts/create_data_provenance_summary.py:9 in public function `main`:
        D103: Missing docstring in public function
scripts/data_aggregation_summary_scripts/create_data_provenance_summary.py:18 in public function `parse_input`:
        D103: Missing docstring in public function
scripts/data_aggregation_summary_scripts/create_data_provenance_summary.py:64 in public function `read_conp_dataset_dir`:
        D103: Missing docstring in public function
scripts/data_aggregation_summary_scripts/create_data_provenance_summary.py:98 in public function `look_for_dats_file_in_subfolders`:
        D103: Missing docstring in public function
scripts/data_aggregation_summary_scripts/create_data_provenance_summary.py:114 in public function `parse_dats_json_file`:
        D103: Missing docstring in public function
scripts/data_aggregation_summary_scripts/create_data_provenance_summary.py:153 in public function `write_csv_file`:
        D103: Missing docstring in public function
scripts/data_aggregation_summary_scripts/create_dataset_statistcs_per_data_providers.py:1 at module level:
        D100: Missing docstring in public module
scripts/data_aggregation_summary_scripts/create_dataset_statistcs_per_data_providers.py:8 in public function `main`:
        D103: Missing docstring in public function
scripts/data_aggregation_summary_scripts/create_dataset_statistcs_per_data_providers.py:43 in public function `parse_input`:
        D202: No blank lines allowed after function docstring (found 1)
scripts/data_aggregation_summary_scripts/create_dataset_statistcs_per_data_providers.py:43 in public function `parse_input`:
        D401: First line should be in imperative mood (perhaps 'Create', not 'Creates')
scripts/data_aggregation_summary_scripts/create_dataset_statistcs_per_data_providers.py:101 in public function `parse_dats_information`:
        D202: No blank lines allowed after function docstring (found 1)
scripts/data_aggregation_summary_scripts/create_dataset_statistcs_per_data_providers.py:101 in public function `parse_dats_information`:
        D205: 1 blank line required between summary line and description (found 0)
scripts/data_aggregation_summary_scripts/create_dataset_statistcs_per_data_providers.py:101 in public function `parse_dats_information`:
        D103: Missing docstring in public function
tests/functions.py:235 in public function `get_filenames`:
        D103: Missing docstring in public function
tests/functions.py:272 in public function `download_files`:
        D103: Missing docstring in public function
tests/functions.py:312 in public function `get_approx_ksmallests`:
        D103: Missing docstring in public function
tests/functions.py:374 in public function `get_sample_files_size`:
        D103: Missing docstring in public function
tests/template.py:1 at module level:
        D200: One-line docstring should fit on one line with quotes (found 2)
tests/template.py:24 in public function `delay_rerun`:
        D103: Missing docstring in public function
tests/template.py:32 in public class `Template`:
        D101: Missing docstring in public class
tests/template.py:34 in public method `install_dataset`:
        D102: Missing docstring in public method
tests/template.py:41 in public method `test_has_readme`:
        D102: Missing docstring in public method
tests/template.py:48 in public method `test_has_valid_dats`:
        D102: Missing docstring in public method
tests/template.py:99 in public method `test_download`:
        D102: Missing docstring in public method
tests/template.py:118 in public method `test_files_integrity`:
        D102: Missing docstring in public method
scripts/data_aggregation_summary_scripts/create_tools_statistics_per_domain.py:1 at module level:
        D100: Missing docstring in public module
scripts/data_aggregation_summary_scripts/create_tools_statistics_per_domain.py:8 in public function `main`:
        D103: Missing docstring in public function
scripts/data_aggregation_summary_scripts/create_tools_statistics_per_domain.py:50 in public function `parse_input`:
        D202: No blank lines allowed after function docstring (found 1)
scripts/data_aggregation_summary_scripts/create_tools_statistics_per_domain.py:50 in public function `parse_input`:
        D401: First line should be in imperative mood (perhaps 'Create', not 'Creates')
scripts/data_aggregation_summary_scripts/create_tools_statistics_per_domain.py:108 in public function `parse_json_information`:
        D202: No blank lines allowed after function docstring (found 1)
scripts/data_aggregation_summary_scripts/create_tools_statistics_per_domain.py:108 in public function `parse_json_information`:
        D205: 1 blank line required between summary line and description (found 0)
scripts/data_aggregation_summary_scripts/create_tools_statistics_per_domain.py:108 in public function `parse_json_information`:
        D400: First line should end with a period (not 'r')
scripts/data_aggregation_summary_scripts/create_tools_statistics_per_domain.py:140 in public function `get_stats_per_domain`:
        D202: No blank lines allowed after function docstring (found 1)
scripts/data_aggregation_summary_scripts/create_tools_statistics_per_domain.py:140 in public function `get_stats_per_domain`:
        D205: 1 blank line required between summary line and description (found 0)
scripts/data_aggregation_summary_scripts/create_tools_statistics_per_domain.py:140 in public function `get_stats_per_domain`:
        D400: First line should end with a period (not ')')
scripts/data_aggregation_summary_scripts/create_tools_statistics_per_domain.py:140 in public function `get_stats_per_domain`:
        D401: First line should be in imperative mood (perhaps 'Produce', not 'Produces')
scripts/conp_to_nidm_terms/report_generator.py:1 at module level:
        D100: Missing docstring in public module
scripts/conp_to_nidm_terms/report_generator.py:10 in public function `main`:
        D103: Missing docstring in public function
scripts/conp_to_nidm_terms/report_generator.py:77 in public function `help_info`:
        D103: Missing docstring in public function
tests/create_tests.py:1 at module level:
        D100: Missing docstring in public module
tests/create_tests.py:10 in public function `get_datasets`:
        D103: Missing docstring in public function
scripts/dats_validator/__init__.py:1 at module level:
        D104: Missing docstring in public package
tests/__init__.py:1 at module level:
        D104: Missing docstring in public package
```

**Comment by mathdugre** [comment]
@cmadjar , I did not touch mypy, flake8, and pydocstyle yet so I expect them to fail. Those will require some time to fix and might better to do them and multiple other PRs. That is, writting the documentation for all the code base might delay this issue for quite a while.

---
## Type hinting with mypy
Also, the type annotation syntax (tested by mypy) changed quite a bit until python3.9. The CI is currently using Python3.6.
We might want to discuss which Python version we want to use for development; @joeyzhou98 @glatard any thought on that?.

**Comment by joeyzhou98** [comment]
> We might want to discuss which Python version we want to use for development; @joeyzhou98 @glatard any thought on that?.

Latest the better in my opinion

**Comment by mathdugre** [comment]
> About about the `check-builtin-literals`? This one also fails as you can see below.

@cmadjar , good catch. I forgot to push the commit. It should be fixed now.

**Review by cmadjar — APPROVED** [review]
👍

**Comment by cmadjar** [comment]
@mathdugre Circle CI error: 

```
collection failure
tests/test_dats_validator.py:6: in <module>
    from ..scripts.dats_validator.validator import REQUIRED_EXTRA_PROPERTIES
E   ValueError: attempted relative import beyond top-level package
```
I think there should be three dots before `scripts` or remove `scripts` and keep the two dots? Unless I am misunderstanding this: https://docs.python.org/3/reference/import.html#package-relative-imports

precommit error as well:
```
flake8...................................................................Failed
- hook id: flake8
- exit code: 1

tests/test_dats_validator.py:43:9: B017 assertRaises(Exception): should be considered evil. It can lead to your test passing even if the code being tested is never executed due to a typo. Either assert for a more specific exception (builtin or custom), use assertRaisesRegex, or use the context manager form of assertRaises.
tests/test_dats_validator.py:51:9: B017 assertRaises(Exception): should be considered evil. It can lead to your test passing even if the code being tested is never executed due to a typo. Either assert for a more specific exception (builtin or custom), use assertRaisesRegex, or use the context manager form of assertRaises.
```

**Comment by mathdugre** [comment]
@cmadjar, the CircleCI issue should be fixed now.

As for the remaining  issues with myp, flake8, and pydocstyl, we might want to solve them in further PRs to reduce merge conflicts.

**Comment by cmadjar** [comment]
Perfect! Thank you @mathdugre

**Pull request merged**
