### PR TITLE
BigBrain_BigBrainWarp_Support: [ADD] crawled dataset.

### PR DESCRIPTION
**Pull request by mathdugre**
## Description

This PR integrate one of the missing bigbrain derivatives listed in #621 .

## Checklist

Mandatory files and elements:
- [x] A `README.md` file, at the root of the dataset
- [x] A `DATS.json` file, at the root of the dataset
- [ ] If configuration is required (for instance to enable a special remote), a `config.sh` script at the root of the dataset
- [ ] A DOI (see instructions in [contribution guide](https://github.com/CONP-PCNO/conp-dataset/blob/master/.github/CONTRIBUTING.md), and corresponding badge in `README.md`

Functional checks:
- [x] Dataset can be installed using DataLad, recursively if it has sub-datasets
- [x] Every data file has a URL
- [x] Every data file can be retrieved or requires authentication
- [x] `DATS.json` is a valid DATs model
- [x] If dataset is derived data, raw data is a sub-dataset

## Related issues (optional)

#621

### CODE REVIEW

**Review by cmadjar — CHANGES_REQUESTED** [review]
@mathdugre same comment about the missing bigbrain-datalad module.

Also, could you modify the values for dataset size and number of files accordingly in the DATS file? I don't think I have the proper value displayed for size directly from the mount of the FTP site. It seems too low to me. Thank you! (To be done for all BigBrain datasets you crawled)

**Review by cmadjar — COMMENTED** [review]
This looks good to me. 

@emmetaobrien would you mind reviewing this PR as well? Another eye on the README and DATS files would be welcome :). Thank you!

**Comment by emmetaobrien** [comment]
I have made some minor edits to README.md and the description field in DATS.json, correcting typos and grammar. Other than that the files look fine to me.

**Comment by cmadjar** [comment]
Thank you @emmetaobrien!

@mathdugre can you update your PR to point to the latest commit of BigBrainWarp_Support? Thanks!

**Pull request merged**
