### PR TITLE
Change to CircleCI dependencies caching

### PR DESCRIPTION
**Pull request by mathdugre**
## Description

This PR as for goal to reduce failures of the CircleCI pipeline after changing the dependencies of the project. See #549 for further detail.

The proposed solution is to merge all the *requirements.txt* in the repository and take unique values. Then calculate the checksum as a key to the cache. This way, the versioning of the cache would be done automatically as users change the dependencies.

Note: Having different **strict** versions of the same dependencies in two separates files will cause a failure of the pipelines.
e.g. `datalad==1.0.0` in */requirements.txt* and `datalad==1.1.1` in */scripts/requirements.txt*.

## Related issues (optional)

Issue #549

### CODE REVIEW

**Comment by cmadjar** [comment]
@mathdugre failing circle CI

**Comment by cmadjar** [comment]
@mathdugre could you merge master into your branch? The issue reported in Circle CI should be fixed now in master. Thanks!

**Comment by cmadjar** [comment]
@mathdugre there are conflicts with the master branch, probably cause by the merge of your PR #551... Sorry.

I also looked at the Circle CI issue. This is one file that is always failing the tests, not because it cannot be downloaded but because the file takes time to be downloaded (probably because it was extracted from a zip file on Zenodo). Not sure what to do with this. I usually restart the Circle CI job hoping it will not try to download that file again but I am sure there are better ways to deal with this ;).

**Comment by mathdugre** [comment]
@cmadjar, just fixed the merge conflict, and the tests are passing now :+1: .

I agree that the download timeout could be problematic when it comes to downloading archives from Zenodo. I opened #554 to further discuss this issue.

**Review by cmadjar — APPROVED** [review]
LGTM 👍 

Thank you @mathdugre!

**Pull request merged**
