### PR TITLE
[Dataset] Add PREVENT-AD Open

### PR DESCRIPTION
**Pull request by paiva**

### CODE REVIEW

**Comment by paiva** [comment]
@PapillonMcGill how about now?

**Comment by PapillonMcGill** [comment]
@paiva Have you done a commit? I see no change.

**Comment by paiva** [comment]
@PapillonMcGill can you try now? It should be consistent

**Comment by jbpoline** [comment]
Just checked with @paiva  that this urls are fine and you can download files when authenticated in loris, merging. 

Still : DATS model should be in the dataset

**Pull request merged**
