### PR TITLE
Add two extra checks in types validation

### PR DESCRIPTION
**Pull request by zxenia**
## Description
This PR adds two checks for a required `'types'` property:
1. checks for an empty object inside of the types list
2. addresses this issue #657 - checks that only data_type_schema properties are present and there are no additional properties.

## Related issues (optional)
#657

### CODE REVIEW

**Comment by zxenia** [comment]
This PR will require fixing DATS for several datasets that fail validation.

The **old version** of `types` that fails validation now (example is taken from DATS file of the PERFORM dataset):

```
"types": [
        {
            "identifier": {
                "identifier": "113091000",
                "identifierSource":"http://purl.bioontology.org/ontology/SNOMEDCT/113091000"
            },
            "value": "MRI"
        },
        {
            "information": {
                "value": "EEG"
            }
        },
        {
            "identifier": {
                "identifier": "ilx_0381893",
                "identifierSource":"http://uri.interlex.org/base/ilx_0381893"
            },
            "value": "quality control subject"
        }
    ],
```

It fails because `identifier` and `identifierSource` properties are **not** in [data_type_schema](https://github.com/CONP-PCNO/schema/blob/master/data_type_schema.json).

So in order to pass validation and be consistent with the schema this part has to be transformed into the following:

```
"types": [
        {
            "information": {
                "value": "EEG"
            }
        },
		{
            "information": {
                "value": "MRI",
		"valueIRI": "http://purl.bioontology.org/ontology/SNOMEDCT/113091000"
            }
        },
		{
            "information": {
                "value": "quality control subject",
		"valueIRI": "http://uri.interlex.org/base/ilx_0381893"
            }
        }
    ],
```

**Comment by cmadjar** [comment]
@zxenia Emmet fixed all of those last week and the changes have been pulled on master. Could you merge the master branch of CONP-PCNO/conp-dataset into you branch? That should fix the tests.

Thank you!

**Comment by cmadjar** [comment]
@zxenia @emmetaobrien 

The tests report 4 errors:
- [x] PERFORM dataset species field: fixed on master now so will be corrected by a merge of master
- [ ] cneuromod - types: the key identifier is not supported by the schema
- [ ] Brainspan - types: the key identifier is not supported by the schema x 18
- [ ] Braincode Mouse Image - types: the key value is not supported by the schema

@emmetaobrien when you get back, could you take a look at the three datasets that remain to be fixed above? I don't remember if we need to contact the owner too for those so they can update on their end as well. Thank you!

**Comment by zxenia** [comment]
@cmadjar Now all DATS validation errors are fixed except the one for [PERFORM_Dataset__one_control_subject](https://github.com/conp-bot/conp-dataset-PERFORM-Dataset-one-control-subject). This dataset's DATS is provided by conp-bot so it'll need to be resubmitted to the conp-bot.
How should we go about it? or shall we merge the PR?

**Comment by emmetaobrien** [comment]
I have manually edited the PERFORM DATS.json and mailed a copy of the most up-to-date version to @mathdugre to update at the source, so when he does that and the dataset is recrawled that should fix this issue.

**Comment by zxenia** [comment]
@emmetaobrien great, thank you!

**Comment by emmetaobrien** [comment]
For reference: the most recent commits:
- update reference genome link in `refseq/refseq_Homo_sapiens`
- add updated `DATS.json` to `mica-mics`

**Review by cmadjar — APPROVED** [review]

**Comment by zxenia** [comment]
Yay it's done! Thanks, everyone!

**Pull request merged**
