### PR TITLE
Perform dats.json

### PR DESCRIPTION
**Pull request by PapillonMcGill**
## Description
adding a dats.json file to PERFORM

## Checklist

Mandatory files and elements:
- [ ] A `README.md` file, at the root of the dataset
- [ ] A `dats.json` file, at the root of the dataset
- [ ] If configuration is required (for instance to enable a special remote), a `config.sh` script at the root of the dataset
- [ ] A DOI (see instructions in [contribution guide](https://github.com/CONP-PCNO/conp-dataset/blob/master/.github/CONTRIBUTING.md), and corresponding badge in `README.md`

Functional checks:
- [ ] Dataset can be installed using DataLad, recursively if it has sub-datasets
- [ ] Every data file has a URL
- [ ] Every data file can be retrieved or requires authentication
- [ ] `dats.json` is a valid DATs model
- [ ] If dataset is derived data, raw data is a sub-dataset

### CODE REVIEW

**Comment by glatard** [comment]
@mathdugre, this one is for you!

**Comment by mathdugre** [comment]
Hi @PapillonMcGill, I am currently working on adding the `dats.json` file, however, I wasn't not sure were to find the PERFORM datasets metadata.

**Comment by PapillonMcGill** [comment]
@mathdugre From the blame, it look like @jbpoline initially added this dataset.

**Comment by mathdugre** [comment]
@PapillonMcGill @glatard , It seems that the `dats.json` was already added to the PERFORM repo on the master branch [here](https://github.com/conpdatasets/PERFORM/blob/master/dats.json).

Unfortunately, the git submodule folder for `/project/PERFORM` seems out-of-date.
Updating the submodule in the remote repository should do the job.

**Comment by PapillonMcGill** [comment]
@mathdugre effectively, after this PR is merged, the dats file will be included here to.

**Comment by glatard** [comment]
@mathdugre the Travis build went one step further, progress! However, the PERFORM test still fails and it is not supposed to happen since "hitting authentication" should be a pass. Would you like to have a look at it? The tests were written by @joeyzhou98, you might want to chat with him in case the behavior is unclear.

**Pull request merged**
