### PR TITLE
Updating DATS.json file format to include access->authorizations

### PR DESCRIPTION
**Pull request by emmetaobrien**
This PR updates the DATS.json files for 22 datasets to include the field  _distributions->access->authorizations_, which can contain the values "public", "registered" or "private". if this field is absent, the desired behaviour is for the value to be treated as "public".  Relevant files in conp-documentation are being updated appropriately.

This PR updates every dataset in CONP-PCNO/conp-dataset except for PERFORM and Learning_Naturalistic_Structure (obtained via conp-bot) and mcgill-emc-rna-seq-experiment (in @zxenia's repository).

### CODE REVIEW

**Comment by emmetaobrien** [comment]
Please do not merge this PR for the moment as datalad appears to have archived the DATS.json files again.

**Comment by emmetaobrien** [comment]
The issue with annexed DATS.json files has been repaired, so  this PR is now ready to merge.

**Comment by glatard** [comment]
Hi @emmetaobrien, this PR has conflicts, would you like to look at it?

**Comment by emmetaobrien** [comment]
@glatard : Those conflicts were due to two of the datasets I mentioned this PR not updating being independently updated, and I have now updated my fork so that those are resolved.

**Comment by emmetaobrien** [comment]
All right, I have just updated those two files accordingly.

**Pull request merged**
