### PR TITLE
fix isAbout according to standard

### PR DESCRIPTION
**Pull request by PapillonMcGill**
## Description
fixing the IsAbout field with the new standard
## Checklist

Mandatory files and elements:
- [x ] A `README.md` file, at the root of the dataset
- [x ] A `DATS.json` file, at the root of the dataset
- [x ] If configuration is required (for instance to enable a special remote), a `config.sh` script at the root of the dataset
- [x ] A DOI (see instructions in [contribution guide](https://github.com/CONP-PCNO/conp-dataset/blob/master/.github/CONTRIBUTING.md), and corresponding badge in `README.md`

Functional checks:
- [x ] Dataset can be installed using DataLad, recursively if it has sub-datasets
- [x ] Every data file has a URL
- [x ] Every data file can be retrieved or requires authentication
- [x ] `DATS.json` is a valid DATs model
- [x ] If dataset is derived data, raw data is a sub-dataset

## Related issues (optional)
#537

### CODE REVIEW

**Review by cmadjar — CHANGES_REQUESTED** [review]
@PapillonMcGill Looks great! Two things:

- the PERFORM dataset is a crawler dataset so we should not be changing the DATS file ourselves but ask the PERFORM people to update their DATS file on the Zenodo platform so our crawlers can pick that up.
- why is was the file Homo_sapiens.gff.gz changed for refseq_Homo_sapiens? Is it related to why Circle CI is failing in https://github.com/CONP-PCNO/conp-dataset/pull/531?

**Comment by cmadjar** [comment]
@PapillonMcGill I think you need to merge conp-dataset/master to your branch to resolve the conflicts.

**Comment by emmetaobrien** [comment]
@PapillonMcGill: can you confirm that your branch incorporated my most recent changes to refseq_Homo_sapiens?

**Comment by PapillonMcGill** [comment]
@cmadjar  I will remove PERFORM.
I did merge from conp-dataset/master. 
Conflict might be due to not include latest change a pointed by @emmetaobrien

**Comment by PapillonMcGill** [comment]
Latest change should have been included as I did a checkout master before editing.
Is it possible to see what conflict are? I tried to see where a conflict could come from in the SIMON dataset except maybe redo @emmetaobrien changes

**Pull request closed without merging**
