### PR TITLE
Adding CONP_status to DATS.json

### PR DESCRIPTION
**Pull request by emmetaobrien**
## Description

This PR adds one additional field to DATS.json for 10 of the datasets in CONP (1000GenomesProject, Brainspan, celltypes, mm_neo_atlas, multicenter-phantom, nhpatlas, preventad-open, refseq, SIMON-dataset and visual-working-memory), *extra_properties->CONP_status*, to indicate which category the dataset should be labelled as in the CONP portal.   Valid values are "CONP", "Canadian" or "external".  Equivalent values have been independently added to the six openpain datasets in separate PRs.

~~The values included are reasonable best estimates based on other metadata, and are not meant to be final.  The purpose of submitting this PR before receiving final confirmed values is to have the data structure in place so that front-end development can proceed; the expected outcome is that it should be possible to develop the desired visual distinction between the three categories in the interface even if category assignations of individual datasets needs correction later.~~ Final values have now been obtained and entered in the *extraProperties->CONP_status* field as appropriate

### CODE REVIEW

**Comment by PapillonMcGill** [comment]
Naser will provide the list this afternoon. We could wait until then to correct/approve.

**Comment by emmetaobrien** [comment]
Sounds good to me.

**Comment by PapillonMcGill** [comment]
How to specify that one of the extraProperties' array item must contain a "CONP_status"? 

If we had another fields outside of the array, we will break backward compatibility. But as done in this PR to preserve backward compatibility, I don't see how it is possible to make it required in the schema.

**Comment by emmetaobrien** [comment]
I have now received Naser's assignments for each dataset and updated the repository accordingly.  While doing so I noticed that .gitmodules for some of the public datasets pointed to copies in my repository rather than at conpdatasets so I have corrected this also.

**Comment by gi114** [comment]
Hi @PapillonMcGill which DATS validator are you currently using ? Would you share it with me so I can catch up on that. In case we might have to edit the validator to approve that item.

**Comment by PapillonMcGill** [comment]
@gi114 The validator is https://github.com/CONP-PCNO/dats-validator

**Pull request merged**
