### PR TITLE
correctly downloading datalad links for 1KGP data, and JSON for reference genome sequences

### PR DESCRIPTION
**Pull request by emmetaobrien**
This update includes regenerated links for 1KGP data which successfully download the data files, though they may need running

git config annex.web-options "-4"

to force git-annex to use curl for the transfer.  (If this causes any other effects. 

git config annex.web-options ""

restores default behaviour.)  This configuration change is a temporary fix while David Bujold looks into correcting the headers on the source files, but was necessary in order to correct issues downstream; I am not sure what the timing on correction of the source file headers is likely to be but it may well have been done by the time you get to test this.

The update also adds three DATS format JSON files under metadata/examples, for the reference genome sequences of Homo sapiens, Mus musculus, and Callithrix japonicus (marmoset), and a scripts folder under projects/1KGP  containing:

1000genomes_table.txt: sql statement used to create the table holding the vcf data in My SQL.

1000genomes_vcf_load.pl: perl script to scan the source data's front page and retrieve a list of URLs; in practice, the unzipped .vcf files were cumbersome so this picks a single one rather than looping through all of them.  It then downloads and unzips the file and scans through it for a count of documented single nucleotide polymorphisms and indels, and writes these counts and other data to the MySQL database.

1000genomes_output_csv.pl: perl script to output genome data in csv format (for test purposes).

1000genomes_output_DATS_json.pl: perl script to output genome data in DATS format JSON.

 1000genomes_output_BioSchema_json.pl: perl script to output genome data in BioSchema-compatible JSON.

These scripts all use the modules DBI and DBD::mysql for database connection, and 1000genomes_vcf_load.pl also uses WWW::Mechanize for spidering and LWP::Simple for retrieving the contents of URLs

validate_json.pl: perl script to validate a user-specified JSON file against a user-specified JSON schema.  Uses the modules JSON and JSON::Validator. 

1000genomes_output_csv.

### CODE REVIEW

**Comment by paiva** [comment]
Hi @emmetaobrien, could you update your `.gitmodules` file please? 

Thanks!

**Comment by glatard** [comment]
Hi, this doesn't seem to be working here:
```
(datalad) [glatard@sapajou 1KGP]$ git config annex.web-options "-4"
(datalad) [glatard@sapajou 1KGP]$ datalad get 1KGP_chr10.vcf.gz 
[WARNING] Running get resulted in stderr output: download failed: InvalidHeader "preload"
git-annex: get: 1 failed
 
[ERROR  ] from web...; Unable to access these remotes: web; Try making some of these repositories available:; 	00000000-0000-0000-0000-000000000001 -- web;  	20e050b1-5ab9-4881-bf53-69f87b84f65e -- emmet@emmet-VirtualBox:~/conp-dataset/projects/1KGP; ; (Note that these git remotes have annex-ignore set: origin) [get(/home/glatard/data/conp-dataset/projects/1KGP/1KGP_chr10.vcf.gz)] 
get(error): /home/glatard/data/conp-dataset/projects/1KGP/1KGP_chr10.vcf.gz (file) [from web...; Unable to access these remotes: web; Try making some of these repositories available:; 	00000000-0000-0000-0000-000000000001 -- web;  	20e050b1-5ab9-4881-bf53-69f87b84f65e -- emmet@emmet-VirtualBox:~/conp-dataset/projects/1KGP; ; (Note that these git remotes have annex-ignore set: origin)]

```
Any idea what could go wrong?

**Comment by jbpoline** [comment]
Same issue on my side (same output as Tristan)

Also tried : 
```
git[master] $ git annex get 1KGP_chr15.vcf.gz
get 1KGP_chr15.vcf.gz (from web...) 
download failed: InvalidHeader "preload"

  Unable to access these remotes: web

  Try making some of these repositories available:
  	00000000-0000-0000-0000-000000000001 -- web
   	20e050b1-5ab9-4881-bf53-69f87b84f65e -- emmet@emmet-VirtualBox:~/conp-dataset/projects/1KGP

  (Note that these git remotes have annex-ignore set: origin)
failed
git-annex: get: 1 failed
```

Also, there is no "description" field in the master DATS model, may be something like:
    "description": "The 1000 genome project dataset : variant call format files containing information about sequence polymorphisms on all chromosome  in 1092 human genomes",

The DATS file should be eventually committed in the dataset as a "git" file

**Comment by glatard** [comment]
@jbpoline the URL is accessible but the server sends a header that trips git-annex while curl and wget are more lenient. See discussion in #14.

**Comment by jbpoline** [comment]
yes, I finally realized that :) We may have to ask Joey to be less stringent on his side if that's the right solution

**Comment by glatard** [comment]
Joey did it already, see https://github.com/snoyberg/http-client/pull/399

**Comment by jbpoline** [comment]
@emmetaobrien : sorry, it seems I have still the same issue : let me know if I have missed something, here is the output of a few commands:

t-jb:~/data/tmp/conp-dataset/projects/1KGP-21May2019
git[master] $ datalad --version
datalad 0.11.4
t-jb:~/data/tmp/conp-dataset/projects/1KGP-21May2019
git[master] $ git annex version
git-annex version: 7.20190219+git191-g2d6a364d4-1~ndall+1
build flags: Assistant Webapp Pairing S3(multipartupload)(storageclasses) WebDAV Inotify DBus DesktopNotify TorrentParser MagicMime Feeds Testsuite
dependency versions: aws-0.20 bloomfilter-2.0.1.0 cryptonite-0.25 DAV-1.3.3 feed-1.0.0.0 ghc-8.4.4 http-client-0.5.13.1 persistent-sqlite-2.8.2 torrent-10000.1.1 uuid-1.3.13 yesod-1.6.0
key/value backends: SHA256E SHA256 SHA512E SHA512 SHA224E SHA224 SHA384E SHA384 SHA3_256E SHA3_256 SHA3_512E SHA3_512 SHA3_224E SHA3_224 SHA3_384E SHA3_384 SKEIN256E SKEIN256 SKEIN512E SKEIN512 BLAKE2B256E BLAKE2B256 BLAKE2B512E BLAKE2B512 BLAKE2B160E BLAKE2B160 BLAKE2B224E BLAKE2B224 BLAKE2B384E BLAKE2B384 BLAKE2S256E BLAKE2S256 BLAKE2S160E BLAKE2S160 BLAKE2S224E BLAKE2S224 BLAKE2SP256E BLAKE2SP256 BLAKE2SP224E BLAKE2SP224 SHA1E SHA1 MD5E MD5 WORM URL
remote types: git gcrypt p2p S3 bup directory rsync web bittorrent webdav adb tahoe glacier ddar hook external
operating system: linux x86_64
supported repository versions: 5 7
upgrade supported from repository versions: 0 1 2 3 4 5 6
local repository version: 5
t-jb:~/data/tmp/conp-dataset/projects/1KGP-21May2019
git[master] $ 
t-jb:~/data/tmp/conp-dataset/projects/1KGP-21May2019
git[master] $ git config annex.web-options "-4"
t-jb:~/data/tmp/conp-dataset/projects/1KGP-21May2019
git[master] $ datalad get 1KGP_chr4_vcf.gz
[WARNING] Running get resulted in stderr output: download failed: Unsupported url scheme ftp://ftp.1000genomes.ebi.ac.uk/vol1/ftp/release/20130502/ALL.chr4.phase3_shapeit2_mvncall_integrated_v5a.20130502.genotypes.vcf.gz
git-annex: get: 1 failed
 
[ERROR  ] from web...; Unable to access these remotes: web; Try making some of these repositories available:; 	00000000-0000-0000-0000-000000000001 -- web; ; (Note that these git remotes have annex-ignore set: origin) [get(/home/jb/data/tmp/conp-dataset/projects/1KGP-21May2019/1KGP_chr4_vcf.gz)] 
get(error): /home/jb/data/tmp/conp-dataset/projects/1KGP-21May2019/1KGP_chr4_vcf.gz (file) [from web...; Unable to access these remotes: web; Try making some of these repositories available:; 	00000000-0000-0000-0000-000000000001 -- web; ; (Note that these git remotes have annex-ignore set: origin)]
t-jb:~/data/tmp/conp-dataset/projects/1KGP-21May2019
git[master] $ git config annex.web-options "-4"
t-jb:~/data/tmp/conp-dataset/projects/1KGP-21May2019
git[master] $ git annex get 1KGP_chr4_vcf.gz
get 1KGP_chr4_vcf.gz (from web...) 
download failed: Unsupported url scheme ftp://ftp.1000genomes.ebi.ac.uk/vol1/ftp/release/20130502/ALL.chr4.phase3_shapeit2_mvncall_integrated_v5a.20130502.genotypes.vcf.gz

  Unable to access these remotes: web

  Try making some of these repositories available:
  	00000000-0000-0000-0000-000000000001 -- web

  (Note that these git remotes have annex-ignore set: origin)
failed
git-annex: get: 1 failed
t-jb:~/data/tmp/conp-dataset/projects/1KGP-21May2019

**Comment by emmetaobrien** [comment]
@jbpoline: I am getting the same failure mode as you do, using the same versions of git-annex and datalad with these files.

**Comment by emmetaobrien** [comment]
However, with datalad 0.9.3 and git-annex 6.20180227 (in the repositories that come with Ubuntu 18.04) these data files are downloading successfully.

**Comment by paiva** [comment]
Emmet opened #47 instead, closing this PR.

**Pull request closed without merging**
