### PR TITLE
Fix download for restricted dataset on Zenodo

### LINKED ISSUE #292: Error during PERFORM dataset installation
Installation of PERFORM dataset errors during test; see [logs](https://app.circleci.com/pipelines/github/mathdugre/conp-dataset/256/workflows/c52eba14-d3d4-4948-8385-6d48e742261b/jobs/547/tests) for more infos.

## Current Behavior

```
/home/circleci/conp-dataset/projects/PERFORM_Dataset__one_control_subject/candidates/913174/V1/instruments/913174_V1_Sleep_Diary
from datalad-archives...; Unable to access these remotes: datalad-archives; Try making some of these repositories available:; 	07f926fa-4dc9-4ac1-a0bc-6032e21f5a64 -- crawler@jacob.novalocal:~/conp-dataset/projects/PERFORM_Dataset__one_control_subject;  	b0874230-9078-4512-9bf1-0a0b2df9301b -- crawler@jacob.novalocal:~/conp-dataset/projects/PERFORM_Dataset__one_control_subject;  	c04eb54b-4b4e-5755-8436-866b043170fa -- [datalad-archives];  	da252973-7a85-4a48-9f10-fa3edf85e562 -- f63a2127faa3:/workdir/projects/PERFORM_Dataset__one_control_subject; ; (Note that these git remotes have annex-ignore set: origin)
```

## Environment (optional)

```bash
docker run --rm -it mathdugre/conp-dataset:v1
python -m venv venv
. venv/bin/activate
export PATH=~/git-annex.linux/:$PATH
git clone https://github.com/mathdugre/conp-dataset.git
cd conp-dataset
git checkout split-test
find . -name requirements.txt | xargs -I{} pip install -r {}
python tests/create_tests.py
PYTHONPATH=$PWD pytest -vs -rfEs tests/test_projects_PERFORM_Dataset__one_control_subject.py
```

### PR DESCRIPTION
**Pull request by mathdugre**
## Description

Those changes fix the test to download PERFORM dataset.

Change brought:
1. Running the dataset config script before starting the download.
1. When download fails, try to download the dataset archive then retry the download.

## Related issues
fix #292

### CODE REVIEW

**Comment by cmadjar** [comment]
@mathdugre It looks like this does not pass the test. Could you investigate? Thank you!

**Comment by mathdugre** [comment]
@cmadjar, The tests pass for PERFORM dataset in the [logs](https://app.circleci.com/pipelines/github/mathdugre/conp-dataset/355/workflows/c476a64b-a619-4b75-ba24-bf45604b7af8/jobs/779/parallel-runs/1). The test failure is due to other datasets.
Once this will be merged, it will require setting up the Zenodo Token in CircleCI to observe the same behaviour as in the logs linked above.

**Comment by cmadjar** [comment]
@mathdugre Oh, OK. So I guess this means I don't have permission to merge on this repo since I don't see the nice green on the merge button.

@glatard Let me know if you think I should have permission to merge on this repo. I am fine either way as long as this gets merged eventually. :)

**Comment by cmadjar** [comment]
@emmetaobrien could you update the review of the PR on this one. I just realized this is why I cannot merge the PR and would prefer if you could finalize the review of the PR. Once done, I will merge it.

Thank you!

**Pull request merged**
