### PR TITLE
Update Mus musculus refseq dataset.

### PR DESCRIPTION
**Pull request by emmetaobrien**
This PR updates the gff file in the `refseq_Mus_musculus` dataset to fix the problem identified in https://github.com/CONP-PCNO/conp-dataset/issues/358.

### CODE REVIEW

**Comment by cmadjar** [comment]
@emmetaobrien there are conflicts with the base branch

**Comment by glatard** [comment]
This also updates mcgill-emc-rna-seq-experiment that still seems to have an invalid DATS model, is it desired?

**Comment by glatard** [comment]
(that said, Mus musculus refseq now passes the tests)

**Comment by emmetaobrien** [comment]
@glatard; that "update" to mcgill-emc-rna-seq-experiment was unintentional and has now been fixed.

**Pull request merged**
