### PR TITLE
Added CHBMP as a submodule

### PR DESCRIPTION
**Pull request by cmadjar**
## Description

This adds the Cuban Human Brain Mapping Project (CHBMP) to the CONP super dataset.

Note: the subproject CHBMP has no data yet in the repository, just descriptions of the dataset

## Checklist

Mandatory files and elements:
- [x] A `README.md` file, at the root of the dataset
- [x] A `DATS.json` file, at the root of the dataset
- [ ] If configuration is required (for instance to enable a special remote), a `config.sh` script at the root of the dataset
- [x] A DOI (see instructions in [contribution guide](https://github.com/CONP-PCNO/conp-dataset/blob/master/.github/CONTRIBUTING.md), and corresponding badge in `README.md`

Functional checks:
- [ ] Dataset can be installed using DataLad, recursively if it has sub-datasets
- [ ] Every data file has a URL
- [ ] Every data file can be retrieved or requires authentication
- [ ] `DATS.json` is a valid DATs model
- [ ] If dataset is derived data, raw data is a sub-dataset

### CODE REVIEW

**Comment by cmadjar** [comment]
@emmetaobrien I don't understand the Circle CI error. Do you have an idea of what is wrong?

**Comment by cmadjar** [comment]
@joeyzhou98 I don't understand why circle ci is failing on this PR. 

The title of the failure is "test_has_readme[projects/CHBMP] - tests.test_projects_CHBMP.TestDataset"

The README.md file is in the dataset so I am not sure why I get that error. Could you help me out?

Thank you!

**Comment by joeyzhou98** [comment]
image

@cmadjar the new submodule you added doesn't seem to have a valid hash: https://github.com/conpdatasets/CHBMP/tree/c339bf6127b75b3830a46d45d0de9f978534e358

**Comment by joeyzhou98** [comment]
Probably resulted from the force-push

**Comment by cmadjar** [comment]
@joeyzhou98 how can I fix that?

**Comment by cmadjar** [comment]
Well, I am just going to close this PR and resubmit it.

**Pull request closed without merging**
