### PR TITLE
add submodule, cool

### PR DESCRIPTION
**Pull request by dlq**
Enhanced Points of Interest for Montreal for 2018.  No metadata.

### CODE REVIEW

**Comment by paiva** [comment]
@dlq I forgot to ask, is this a real PR or just to test it out? If it is real, I can start testing it right away

**Comment by dlq** [comment]
Real.  I will update it to be even more real with metadata, etc as I go. 


Darcy

**Comment by paiva** [comment]
Hi @dlq, this PR is good and works well, but we now require that datasets include a dats.json file with metadata about the dataset. We can follow up on this anytime this week.

**Comment by dlq** [comment]
I will resubmit this PR when it’s actually ready. I shouldn’t have let it sit for so long.

**Pull request closed without merging**
