### PR TITLE
[ADD] Automatically label/close stale issues and pull requests.

### PR DESCRIPTION
**Pull request by mathdugre**
## Description

This PR aims to simplify the maintenance of issues and PRs.
The GitHub workflow proposed will automatically label issues and PRs as **stale** after a configured time. If no actions is taken after a set number of days, that issue/pr will be closed automatically.

### Proposed configuration:

- Issues:
  - label stale: 30 days
  - close after labeling: 5 days
- Pull requests:
  - label stale: 45 days
  - close after labeling: 10 days

### CODE REVIEW

**Comment by mathdugre** [comment]
@cmadjar, I took the proposed configuration from GitHub. However, we might want to discuss how long we want an issue/pr to be inactive before labeling it as stale. Also, is auto-closing stale issue/pr a feature we want?

**Comment by emmetaobrien** [comment]
Those seem rather short to me.

**Comment by mathdugre** [comment]
During my last meeting with @glatard, we discussed:
- issues:
    - label: 5 months
    - close: + 3 months
- PR:
    - label: 30 days
    - close: + 10 days

What are your thought on those delays @cmadjar , @emmetaobrien ?

**Comment by emmetaobrien** [comment]
I would certainly agree with that for issues, but I would favour extending the values for PRs a little further, maybe to 45 + 15 or 40 + 20?

We have definitely had some PRs that have stayed active for a while because trying to merge them exposed secondary issues that needed addressing separately, and once those were resolved it was appropriate to then merge the original PR; I do not think such a situation will often stretch out for more than a month, but it seems not impossible in a worst case of other urgent priorities turning up for the people primarily concerned.  I'd been thinking of marking things stale and/or autoclosing them as more applying to issues and PRs from significantly earlier in the project, that are no longer compatible with the structures and procedures we have developed since, and that may well have been submitted by people no longer with CONP.

**Comment by cmadjar** [comment]
I agree! Those seem more realistic.

- issues:
  - label: 5 months
  - close: + 3 months
- PR:
  - label: 45 days
  - close: + 20 days

**Comment by mathdugre** [comment]
I updated the configuration with the latest values from @cmadjar.

**Review by cmadjar — APPROVED** [review]

**Pull request merged**
